### ISSUE TITLE
9700+b360m迫击炮，无法使用屏幕亮度调节

### ISSUE THREAD

**Issue by jinzhen2013** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#10]
麻烦问下这个有解决办法吗？

**Comment by GeQ1an** [comment]
你是指通过系统调节屏幕亮度？
呃...... 我貌似还没有见过可以通过系统调节亮度的显示器，可以手动通过显示器调节。

**Comment by jinzhen2013** [comment]
明白了，感谢

**Comment by derbalkon** [comment]
有些 DP 协议的显示器可以通过 [MonitorControl](https://github.com/the0neyouseek/MonitorControl/releases) 实现系统调节亮度和声音（如果有），HDMI 显示器的话就不好说了。
