### ISSUE TITLE
希望能提供Release下载EFI文件，非常感谢

### ISSUE THREAD

**Issue by GitHubAdminis** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#100]
重复下载多次都提示网络问题导致下载失败，git clone一样下载不下来，速度10KB/s，挂梯子也一样

**Comment by Went1ng** [comment]
1>>简单一点的可以用手机流量去下载，（速度有点慢，但不会断开下载）
2>>注册一个“码云” （具体怎么使用自行百度或其他视频教学网站）
3>>其他方法自行百度或其他视频教学网站
感谢参考
