### ISSUE TITLE
关于更新oc引导后，开机选择开机项的问题

### ISSUE THREAD

**Issue by wswkuo** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#102]
你好，最近更新oc后，开机要赶紧按左右键选择要引导的系统，不然就进第一个。请问oc可以像clover那样开机读秒吗，而且oc好像不能记住我上次用了哪个系统，而clover可以记住，并且下次引导默认为上次引导的系统。

**Comment by Went1ng** [comment]
需要修改EFI的一些参数，建议百度




在2020年09月10日 09:58，wswkuo 写道：

你好，最近更新oc后，开机要赶紧按左右键选择要引导的系统，不然就进第一个。请问oc可以像clover那样开机读秒吗，而且oc好像不能记住我上次用了哪个系统，而clover可以记住，并且下次引导默认为上次引导的系统。

**Comment by Went1ng** [comment]
了解OC的一些简单内容可以看一看这两期视频（视频制作者非本人）
B站:BV1gE411L7Sw，BV1nE411j7Wm




在2020年09月10日 12:44，系统自动 写道：
需要修改EFI的一些参数，建议百度




在2020年09月10日 09:58，wswkuo 写道：

你好，最近更新oc后，开机要赶紧按左右键选择要引导的系统，不然就进第一个。请问oc可以像clover那样开机读秒吗，而且oc好像不能记住我上次用了哪个系统，而clover可以记住，并且下次引导默认为上次引导的系统。

**Comment by wswkuo** [comment]
xx
