### ISSUE TITLE
我的风扇转速监测有问题

### ISSUE THREAD

**Issue by Teraflopst** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#103]
请问风扇监测为什么显示为0rpm，试过各种应用

**Comment by Went1ng** [comment]
bios有吗




在2020年09月16日 08:39，He Wenwei 写道：

请问风扇监测为什么显示为0rpm，试过各种应用

**Comment by Teraflopst** [comment]
> bios有吗
> 
> 
> 
> 
> 在2020年09月16日 08:39，He Wenwei 写道：
> 
> 请问风扇监测为什么显示为0rpm，试过各种应用

BIOS 显示正常。

**Comment by GeQ1an** [comment]
部分软件可能无法识别风扇转速，请通过 [HWMonitorSMC2](https://github.com/CloverHackyColor/HWMonitorSMC2/releases) 查看。
