### ISSUE TITLE
请问这里的0.6.0 OC是否可以直接升级10.15.7 ?

### ISSUE THREAD

**Issue by gogoclothes** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#105]
有升级的朋友麻烦给个参考，谢谢！

**Comment by healyoo** [comment]
现在还有办法下载0.6.0版本的EFI呀？

**Comment by gogoclothes** [comment]
> 现在还有办法下载0.6.0版本的EFI呀？

不是，我没有更新最新的OC，因为是主力机，不想折腾big sur。

**Comment by hforlong** [comment]
我的配置和楼主基本一致，现在是0.6.1，都是直接升级，使用上没有啥问题。

**Comment by gogoclothes** [comment]
> 我的配置和楼主基本一致，现在是0.6.1，都是直接升级，使用上没有啥问题。

非常感谢你的信息～

**Comment by gogoclothes** [comment]
亲测可以直接升级10.15.7，使用上暂时没有问题。
