### ISSUE TITLE
oc更新替换EFI后，为什么查看oc版本显示还是老的版本？

### ISSUE THREAD

**Issue by hainustar** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#106]
楼主，用您的最新oc版本的efi替换旧的引导后，为什么查看oc版本显示还是老的版本？
![image](https://user-images.githubusercontent.com/72779135/95814296-a2817200-0d4c-11eb-8742-0afac9602bf1.png)

**Comment by myd986** [comment]
替换了以后没有重启吗？

**Comment by hainustar** [comment]
关机冷启动过，查看EFI替换是成功的。使用u盘也是这样，好是奇怪。

**Comment by hainustar** [comment]
关机重启过。检查替换的文件，是正常替换过，很是奇怪。

**Comment by myd986** [comment]
nvram重置了吗？

**Comment by hainustar** [comment]
没有哦，怎么重置nvram? 请教！！感谢！

**Comment by hainustar** [comment]
> nvram重置了吗？

感谢。在oc引导界面重置nvram就正常了。

**Comment by GeQ1an** [comment]
这个问题最简单的解决办法貌似就是重置 NVRAM。
