### ISSUE TITLE
能不能出一个核显版本的？

### ISSUE THREAD

**Issue by cmj799** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#108]
我的独立显卡不支持黑苹果。。。

**Comment by Went1ng** [comment]
有哦，需要修改





在2020年10月24日 12:43，cmj799 写道：

我的独立显卡不支持黑苹果。。。

**Comment by cmj799** [comment]
在Windows下我不能直接比较好地修改plist文件，无法使用黑苹果，若是直接有现成的才好办，现在是根本没有方法进黑苹果。。。

**Comment by GeQ1an** [comment]
Windows 环境可使用 [ProperTree](https://github.com/corpnewt/ProperTree) 进行编辑。
