### ISSUE TITLE
i7-9700加公版RX570开机会花屏但能正常进系统使用，第一阶段logo大，会闪一下屏幕之后能正常显示。

### ISSUE THREAD

**Issue by hforlong** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#11]
如题，基本配置和你类似，能够使用。但有点强迫症，请问有解决方案吗，感谢。

**Comment by GeQ1an** [comment]
参考 [Q&A](https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI/blob/master/README.md#qa)

**Comment by hforlong** [comment]
> 参考 [Q&A](https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI/blob/master/README.md#qa)
我看了，试了一下，logo开始还是一大一小，先大后小，后来我弄了一下hidpi,大小一致了。主要问题是花屏，开机通电先花一屏幕之后一切正常，感觉是在引导之前花的，我用的hdmi接口，不过我试了dp接口也花屏，不知道是不是显示器的问题，显示器是华硕ROG PG279Q。

**Comment by GeQ1an** [comment]
emmm…… 也就是说，按下电源键的瞬间就花了，甚至在可以进入 BIOS 之前？

**Comment by hforlong** [comment]
> emmm…… 也就是说，按下电源键的瞬间就花了，甚至在可以进入 BIOS 之前？

对，目前看现象是这样的，我打算先换个显示器试试看一下。

**Comment by hforlong** [comment]
> emmm…… 也就是说，按下电源键的瞬间就花了，甚至在可以进入 BIOS 之前？

目前顺序是开机通电花屏一下，出现bios页面，之后就是oc的引导信息，正常进入系统。
