### ISSUE TITLE
请问支持MAG B365M MORTAR吗?

### ISSUE THREAD

**Issue by wflaowei** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#112]
可以直接通用吗？

**Comment by GeQ1an** [comment]
没有在除该主板外其他任何主板进行测试，请自行测试。

**Comment by wflaowei** [comment]
> 没有在除该主板外其他任何主板进行测试，请自行测试。

感谢，经测试，在独显的情况下，无法驱动核显，更改了id也不行。我自己重新配了一个。

**Comment by tianchaomaker** [comment]
> > 没有在除该主板上其他任何主板进行测试，请自行测试。
> 
> 感谢，经测试，微星H365M MORTAR i5 9500在独显的情况下，无法驱动核显，无法启动硬件加速，更改了id也不行。我自己重新配了一个。

老哥，我也是个你一样的主板和CPU  ，用的核显。能否共享你的EFI谢谢，563716438@qq.com
