### ISSUE TITLE
inter网卡支持

### ISSUE THREAD

**Issue by gumengkai** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#117]
大佬 可否会考虑下支持inter系的网卡，比如ax200? 听说已经有驱动了

**Comment by GeQ1an** [comment]
请自行添加，这个 EFI 追求的是 “完美”，而 Inter 网卡与 “完美” 背道而驰。目前我这里已经是接近完美状态了，除了自检星自检时间过长。

**Comment by milesking** [comment]
> 请自行添加，这个 EFI 追求的是 “完美”，而 Inter 网卡与 “完美” 背道而驰。目前我这里已经是接近完美状态了，除了自检星自检时间过长。
自检真的太慢了，怀念4代的自检速度
