### ISSUE TITLE
无法进入安装引导盘

### ISSUE THREAD

**Issue by destinyfors** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#118]
1.双系统双sdd，硬件和作者一样
2.系统安装器是用的白苹果制作的，appstore下载catalina官方命令写入U盘，OpenCore Configurator挂在U盘的ufi分区，将作者的oc文件填入三码+rom后复制到U盘ufi分区
3.插入电脑设为第一启动项，重启后不显示引导页面，直接进入了win系统（换一个其他的oc文件后可以显示引导页面）

有没有大佬能指点一下

**Comment by Went1ng** [comment]
1你先将windows系统的盘不安装在主板上
2开机bios报错如果是头图这样
![image](https://user-images.githubusercontent.com/67221893/99204188-d4747100-27ef-11eb-9f1e-97077ac6586a.jpeg)
按照图上的提示修改。
（如果你无法进入系统的话，这个参数需要在windows下修改）
［Windows修改参数参考：B站：BV1uf4y1X7MT］

**Comment by destinyfors** [comment]
> 1你先将windows系统的盘不安装在主板上
> 2开机bios报错如果是头图这样
> ![image](https://user-images.githubusercontent.com/67221893/99204188-d4747100-27ef-11eb-9f1e-97077ac6586a.jpeg)
> 按照图上的提示修改。
> （如果你无法进入系统的话，这个参数需要在windows下修改）
> ［Windows修改参数参考：B站：BV1uf4y1X7MT］

谢谢大佬 已经进到引导菜单了
