### ISSUE TITLE
使用U盘引导可以正常睡眠唤醒，将U盘UFI复制到硬盘UFI分区后睡眠死机无法唤醒

### ISSUE THREAD

**Issue by ghost** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#119]
1. 硬件跟作者一样。
2.双ssd双系统。
3.安装好苹果系统后，U盘未拔出直接点击睡眠可以通过键盘鼠标唤醒，唤醒后使用OpenCore Configurator把U盘UFI文件夹复制到硬盘UFI分区，再次点击睡眠后系统无法通过鼠标键盘唤醒，主板等亮，风扇也在转动，只能通过长按电源键强制关机。

求大佬指点。

**Comment by destinyfors** [comment]
> 1. 硬件跟作者一样。
>    2.双ssd双系统。
>    3.安装好苹果系统后，U盘未拔出直接点击睡眠可以通过键盘鼠标唤醒，唤醒后使用OpenCore Configurator把U盘UFI文件夹复制到硬盘UFI分区，再次点击睡眠后系统无法通过鼠标键盘唤醒，主板等亮，风扇也在转动，只能通过长按电源键强制关机。
> 
> 求大佬指点。

经过测试发现，跟引导在U盘和硬盘无关，插网线的情况下睡眠无法唤醒，拔掉网线一切正常，头大。

**Comment by Went1ng** [comment]
系统偏好设置-节能-
只开启第二个：如果可能，使硬盘进入睡眠
第一个，第三个，第四个，第五个都不要打开
___或许有用，但是忘了在哪里看到过

**Comment by Went1ng** [comment]
或许睡眠问题和定制usb有关
建议你完整的定制一下usb
参考：B站BV1rt4y1y7Pb

**Comment by destinyfors** [comment]
> 系统偏好设置-节能-
> 只开启第二个：如果可能，使硬盘进入睡眠
> 第一个，第三个，第四个，第五个都不要打开
> ___或许有用，但是忘了在哪里看到过

谢谢大佬 关闭唤醒以供以太网络访问选项可解决问题
