### ISSUE TITLE
请教作者一个问题关于SSDT-MCHC和SSDT-EC-USBX

### ISSUE THREAD

**Issue by hforlong** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#120]
一直在使用你的efi，十分感谢。我想请教一下，为什么使用了SSDT-MCHC，以及为什么没有使用SSDT-EC-USBX。特别是SSDT-EC-USBX，因为我看了一些资料，这个好像是要用到的，我查了一些资料没有找到合适的答案，所以想请教一下，谢谢。

**Comment by GeQ1an** [comment]
当时 MCHC 用于修正内存控制器，不知道现在是否还需要，下次更新时我会对其进行测试，若不再需要将会被移除。
EC-USBX 用于开启 USB 高功率输出，但当时采用的是用 USBPower.kext 解决该问题，两种方法自己选择即可。

**Comment by hforlong** [comment]
> 当时 MCHC 用于修正内存控制器，不知道现在是否还需要，下次更新时我会对其进行测试，若不再需要将会被移除。
> EC-USBX 用于开启 USB 高功率输出，但当时采用的是用 USBPower.kext 解决该问题，两种方法自己选择即可。

好的，感谢
