### ISSUE TITLE
替换EFI问题

### ISSUE THREAD

**Issue by python8384** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#121]
我用黑过小兵的镜像安装完成后，并开启EFI分区，怎么用up主的OC去替换这个EFI？

**Comment by yansh15** [comment]
在macOS下的话，使用Hackintool工具挂载系统磁盘上的EFI分区，然后复制作者的EFI文件夹覆盖EFI分区里的EFI文件夹即可。

**Comment by python8384** [comment]
好的，谢谢。

**Comment by pkxutao** [comment]
> 在macOS下的话，使用Hackintool工具挂载系统磁盘上的EFI分区，然后复制作者的EFI文件夹覆盖EFI分区里的EFI文件夹即可。

 请问为什么我之前的EFI分区文件夹下是BOOT+CLOVER,但作者的EFI文件夹是BOOT+OC呢？

**Comment by yansh15** [comment]
>  请问为什么我之前的EFI分区文件夹下是BOOT+CLOVER,但作者的EFI文件夹是BOOT+OC呢？

因为作者使用OpenCore（OC）引导，你之前使用的是Clover。所以EFI文件夹里的内容不同。如果是同机型的话替换应该是没问题的，可以**备份原EFI**之后试试。

**Comment by pkxutao** [comment]
> > 请问为什么我之前的EFI分区文件夹下是BOOT+CLOVER,但作者的EFI文件夹是BOOT+OC呢？
> 
> 因为作者使用OpenCore（OC）引导，你之前使用的是Clover。所以EFI文件夹里的内容不同。如果是同机型的话替换应该是没问题的，可以**备份原EFI**之后试试。

你好，还问个问题，怎么制作U盘引导已有的系统呢？网上找到的方案都是用U盘制作新系统，我想测试作者的efi，使用U盘引导已有的系统该怎么做，可以给个关键词吗？

**Comment by yansh15** [comment]
> > > 请问为什么我之前的EFI分区文件夹下是BOOT+CLOVER,但作者的EFI文件夹是BOOT+OC呢？
> > 
> > 
> > 因为作者使用OpenCore（OC）引导，你之前使用的是Clover。所以EFI文件夹里的内容不同。如果是同机型的话替换应该是没问题的，可以**备份原EFI**之后试试。
> 
> 你好，还问个问题，怎么制作U盘引导已有的系统呢？网上找到的方案都是用U盘制作新系统，我想测试作者的efi，使用U盘引导已有的系统该怎么做，可以给个关键词吗？

如果你的U盘是GUID(GPT)分区表的话，挂载U盘的EFI分区然后把作者的EFI文件夹（也许需要你定制修改一下）拷贝进去，然后BIOS设置U盘启动就可以了。如果不是GUID(GPT)的话需要重新格式化了。然后测试的话配置的`ShowPicker`可以改成`True`会好一点。

**Comment by GeQ1an** [comment]
看到大家互相解决问题很好👍🏻
