### ISSUE TITLE
OC 0.6.3  OTA升级  Big Sur  11.1 (20C69) 已安全下车

### ISSUE THREAD

**Issue by FFzt** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#124]
<img width="586" alt="Snipaste_2020-12-16_00-04-11" src="https://user-images.githubusercontent.com/37873312/102240252-9bd0d000-3f32-11eb-9bc3-42cf95acab50.png">
实测修复了以下问题:
1.状态栏图标位置重启失效的问题
2.程序最小化有时会掉帧的问题
3.多屏拖动程序窗口会卡顿的问题
总之体验比上一个版本好很多,没有想要回到Catalina的想法了,初步体验还行

**Comment by GeQ1an** [comment]
谢谢反馈，即将更新 OC 0.6.4

**Comment by FFzt** [comment]
谢谢老大的EFI😁> 谢谢反馈，即将更新 OC 0.6.4

**Comment by xuconnery** [comment]
啊哈，原来是Catalina系统的问题造成的窗口卡顿问题。。。我还一直以为是显卡的问题呢，看来有必要升级到bigsur了

**Comment by FFzt** [comment]
你用的是集显吧，独显Catalina窗口不会卡的啊> 啊哈，原来是Catalina系统的问题造成的窗口卡顿问题。。。我还一直以为是显卡的问题呢，看来有必要升级到bigsur了

**Comment by xuconnery** [comment]
不是啊，570啊

**Comment by INNERJOINT** [comment]
同570 三个屏幕 在catalina下拖动窗口确实有卡顿现象

> 不是啊，570啊
