### ISSUE TITLE
请问 10.15.3 这个系统你是从黑果小兵下载的 还是从 mac的 appstore 下载的 ？

### ISSUE THREAD

**Issue by lbq1223android** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#13]

**Comment by GeQ1an** [comment]
我是在白果 App Store 下载好做的启动盘。在黑果小兵下载也是可以的，注意替换里面的 EFI 和删除 WINPE 就好了。

**Comment by lbq1223android** [comment]
> 我初次安装时系统为 10.15.2，是在白果 App Store 下载后做的启动盘，10.15.3 是直接在系统升级的。在黑果小兵下载镜像也是可以的，注意替换里面的 EFI 分区，最好也将附带的 WINPE 删除。

好的  感谢
