### ISSUE TITLE
休眠唤醒后sidecar随航变得非常卡顿

### ISSUE THREAD

**Issue by shijingkun886** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#134]
你好，我和你配置一模一样，使用你的配置全部都正常，除了休眠唤醒后sidecar随航变得非常卡顿，不知道你有没有相同的问题

**Comment by GeQ1an** [comment]
应该是唤醒后 WiFi 不稳定导致的，可以尝试加载 [AirportBrcmFixup](https://github.com/acidanthera/AirportBrcmFixup/releases/latest) kext 解决，或参考 [Cattyhouse](https://github.com/cattyhouse/oc-guide/blob/master/wifiwake.md) 提供的思路。
