### ISSUE TITLE
请问 公版 RX 570 4GB（由微星代工）  这个显卡你是从哪买的  可否给我个链接 咱俩的硬件大部分相同  感谢

### ISSUE THREAD

**Issue by lbq1223android** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#14]

**Comment by GeQ1an** [comment]
为了避免广告嫌疑，不会公开发送商品链接，需要的话可以在 [Telegram](https://t.me/GeQ1an) 联系我索取。

**Comment by lbq1223android** [comment]
> 为了避免广告嫌疑，不会公开发送商品链接，需要的话可以在 [Telegram](https://t.me/GeQ1an) 联系我索取。

liubq@lenovo-ar.com   我梯子最近断了 上不了tg了  能不能发我邮箱 或者咱们加个微信也行

**Comment by GeQ1an** [comment]
已发送。

**Comment by addio** [comment]
> 为了避免广告嫌疑，不会公开发送商品链接，需要的话可以在 [Telegram](https://t.me/GeQ1an) 联系我索取。

Telegram 能加吗？

**Comment by GeQ1an** [comment]
> > 为了避免广告嫌疑，不会公开发送商品链接，需要的话可以在 [Telegram](https://t.me/GeQ1an) 联系我索取。
> 
> Telegram 能加吗？同问，[gandli@qq.com](mailto:gandli@qq.com)

可以直接在 Telegram 向我发起对话，稍后也会将链接发送到你邮箱。

**Comment by GeQ1an** [comment]
> > 为了避免广告嫌疑，不会公开发送商品链接，需要的话可以在 [Telegram](https://t.me/GeQ1an) 联系我索取。
> 
> Telegram 能加吗？同问，[gandli@qq.com](mailto:gandli@qq.com)

刚刚翻阅订单发现商家已经下架了该显卡，建议在 [淘宝](https://www.taobao.com) 搜索 “联想 RX570” 自行鉴定商家购买。

P.S. 联想款 RX570 由微星代工，且 VBIOS 品牌信息为微星，黑苹果使用兼容性较好。

**Comment by addio** [comment]
> > > 为了避免广告嫌疑，不会公开发送商品链接，需要的话可以在 [Telegram](https://t.me/GeQ1an) 联系我索取。
> > 
> > 
> > Telegram 能加吗？同问，[gandli@qq.com](mailto:gandli@qq.com)
> 
> 刚刚翻阅订单发现商家已经下架了该显卡，建议在 [淘宝](https://www.taobao.com) 搜索 “联想 RX570” 自行鉴定商家购买。
> 
> P.S. 联想款 RX570 由微星代工，且 VBIOS 品牌信息为微星，黑苹果使用兼容性较好。

感谢

**Comment by xiaohu-swjtu** [comment]
同求，麻烦给个链接，1150389202@qq.com
