### ISSUE TITLE
i7 9700 核显 黑屏

### ISSUE THREAD

**Issue by bowenqiang** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#142]
CPU i7 9700, 用了最新的EFI，根据使用核显的说明做了相应的修改。结果还是启动时进度条走了1/3就黑屏无输出。远程控制可以查看到系统已经启动。在Catalina/big sur都是这样，使用了板载的hdmi, dp, dvi接口还是这样。

**Comment by bowenqiang** [comment]
之前是用5700独显的，显示正常。后来独显出售，所以改核显。

**Comment by Went1ng** [comment]
我现在用的是9400核显UHD630
原先的rx570也可以用，

可能是使用5700xt时的需要添加参数防止黑屏。
现在用核显需要删除（agdpmod=pikera）


4K-UHD630记录

之前用京东绿联的dp1.2,在4K下会闪黑屏，睡眠唤醒会闪绿屏后闪黑屏，换了三分之一的价格的戴尔dp1.4就没出现过了

HDMI则开机会在登入账号前黑屏15秒左右，睡眠需要重启显示器，且受限接口只能4K30hz

**Comment by bowenqiang** [comment]
是已经去掉了agdpmod=pikera。但是也是没有用。求分享EFI

**Comment by Went1ng** [comment]
kaipulexing@qq.com 附上主题UHD630

**Comment by bowenqiang** [comment]
已发，好人一生平安

**Comment by bowenqiang** [comment]
好用！
