### ISSUE TITLE
升级Big Sur 11.3.1之后所有usb2.0端口都无法使用

### ISSUE THREAD

**Issue by Aaddonn** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#143]
系统信息-USB那里只显示USB3.1总线，蓝牙也无法使用，这应该表示USB2.0端口全部无法使用，请问应该如何解决？

**Comment by Aaddonn** [comment]
已通过USB定制解决

**Comment by layui0320** [comment]
你好，请问你是在11.3.1系统下定制的吗？我在11.5.2定制usb时主板部分接口不能识别到设备。求解

**Comment by Aaddonn** [comment]
是的，11.3.1系统下定制





------------------ 原始邮件 ------------------
发件人: layui0320 ***@***.***&gt;
发送时间: 2021年9月19日 02:07
收件人: GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI ***@***.***&gt;
抄送: Aaddonn ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI] 升级Big Sur 11.3.1之后所有usb2.0端口都无法使用 (#143)





 
你好，请问你是在11.3.1系统下定制的吗？我在11.5.2定制usb时主板部分接口不能识别到设备。求解
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
