### ISSUE TITLE
蓝牙键盘无法唤醒

### ISSUE THREAD

**Issue by ZipperLi** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#144]
老哥你好，我现在也趋近于完美配置了，但是我有个问题还是想请教下，最近换了蓝牙键盘，正常开关机都没问题，稳定连接，但是我如果触发了睡眠，蓝牙键盘是根本唤醒不了的，我看好像是睡眠过后，蓝牙就直接断开了连接，请问下，这个有木有什么解决办法呢？

**Comment by GeQ1an** [comment]
蓝牙走的是 USB 通道，建议排查睡眠后 USB 是否正常？P.S. 我没有使用过蓝牙键盘，建议多去搜索。

**Comment by GeQ1an** [comment]
今日突然想到一个问题，排查唤醒（无论何种方式唤醒）后蓝牙是否正常？有一些网卡转接板设计缺陷（尤其是 USB 连接线只有两根线的）会导致睡眠后蓝牙丢失，需要唤醒后几分钟才会恢复，这当然也会导致睡眠后蓝牙键盘无法唤醒。
