### ISSUE TITLE
老哥有没有考虑升级到oc0.7.3啊？

### ISSUE THREAD

**Issue by ZipperLi** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#147]
老哥有没有考虑升级到oc0.7.3啊？我自己升级了，但是，图形界面丢失了，，，裂开。。。。

**Comment by Went1ng** [comment]
升级OC7.0后图形引导不能直接拖原来的［Resources］文件夹，要按新的文件层级排列，再修改对应的config数值。

据观察，大概是image文件夹下,不再使用之前使用前缀分类，而是直接使用文件夹分类。

至于其他的，不了解。

仅供参考

**Comment by GeQ1an** [comment]
已更新到 OC 0.7.5 版本。
