### ISSUE TITLE
Monterey 12.0.1 开机过慢

### ISSUE THREAD

**Issue by zhylmzr** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#149]
升级 `Monterey 12.0.1` 后每次开机起码要1分钟。

**Comment by GeQ1an** [comment]
请尝试在`终端`中输入如下命令：
````
log show --last boot | grep "trims took"
````
查看返回结果中的 trims took 时间，如果超过 10 秒，则会导致开机时间变长，目前的解决办法只有更换硬盘。

**Comment by zhylmzr** [comment]
```
2021-12-08 18:23:33.635194+0800 0x411 Default 0x0 0 0 kernel: (apfs) spaceman_scan_free_blocks:3153: disk2 scan took 100.481390 s, trims took 100.332499 s
```
三块硬盘，一块 970 evo 装的 mac，一块海康威视C2000装的 Windows，一块 860 qvo 存放文件

`disk2`挂载的是 970 evo

**Comment by GeQ1an** [comment]
就是这个问题了。升级 12.0.1 后，很多 970 EVO（还有其他三星的固态硬盘）都有这个问题，目前除了换硬盘无解。
