### ISSUE TITLE
请问可以用在10.14.6上吗？

### ISSUE THREAD

**Issue by nathan-code** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#15]
很抱歉打扰了，小白一个，我的目标版本是10.14.6，不知这个EFI可否支持较低的版本？
顺便感谢大佬的共享~~

**Comment by GeQ1an** [comment]
应该支持，可以尝试一下。

**Comment by Bornjackosn** [comment]
楼主你好！！不知道你尝试成功了吗？
我也想做10.14.6因为好多音乐方面的软件会在mojave上更稳定一些！！！
如果成功了的话请务必传授一下心得！！感激不尽！
