### ISSUE TITLE
睡眠唤醒后，有线键盘失效

### ISSUE THREAD

**Issue by yedongxu** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#150]
macOS版本是蒙特雷，先前自己根据其他教程制作efi就有唤醒后键盘失效问题，重新插拔就好了，但是太难受了，鼠标唤醒后可以直接用。后来看到这里的efi，使用u盘制作启动盘，从u盘引导，进入系统，睡眠，唤醒，问题依旧，找了好多天解决办法都没找到。一开始我还以为是个例，现在看来应该是通病了，我已经没辙了，希望up主能早日找到解决办法。

**Comment by GeQ1an** [comment]
既然唤醒后鼠标可用，说明 USB 是工作的，换 EFI 还有这个问题，有没有考虑换个键盘试试呢？
