### ISSUE TITLE
黑苹果系统镜像

### ISSUE THREAD

**Issue by python8384** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#152]
请问使用当前最新发布的EFI采用OC 0.7.7，使用从黑果小兵下载的镜像macOS Monterey 12.1 21C52 Installer for OpenCore 0.7.6 and CLOVER 5143 and WEPE 三 EFI 分区原版镜像，然后直接替换镜像里面的EFI，有没有问题？

**Comment by GeQ1an** [comment]
没有问题，注意完全清空 EFI 分区（建议把 Win PE 也清掉）后，再把 EFI 放进去（最好先填写好三码信息。

**Comment by python8384** [comment]
下载了黑果小兵的macOS Monterey 12.1 21C52 Installer for OpenCore 0.7.6 and CLOVER 5143 and WEPE 和黑苹果星球的黑苹果UEFI镜像macOS Monterey 12.1(21C52)正式版带 OpenCore 0.7.7 和 Clover r5142 以及 WEPE版本，烧录U盘后，选择OC引导，跑码结束后，全部黑屏，而且一直黑屏，只能重启，一直不能继续安装，尝试了很多次，不知道问题出在哪里，是需要在安装之前把U盘里面EFI分区OC里面的内容全部替换成仓库里面的OC吗，硬件配置和你这边的配置是一样的。

**Comment by GeQ1an** [comment]
我有说，完全清空 EFI 分区，再把 EFI 文件夹放进去。这种最基础的问题，建议自己稍微做做功课。
