### ISSUE TITLE
9400单核显，架构及igpu三问号

### ISSUE THREAD

**Issue by reyukari** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#154]
除了架构和核显没驱动外，其他外设表现正常。不知道是不是因为架构和核显，动画和网页很卡。
大佬救，百度无果，oc文档切换到coffee lake 也没有什么需要特别设置的。
核显已经按照无独显使用的指导，添加了字段。
三码和os也有做替换。

图手机拍的
![image](https://user-images.githubusercontent.com/56849388/154261157-eedd4da1-7423-48fa-bade-7e32a940de9a.jpeg)

**Comment by reyukari** [comment]
我首先基于大佬您的无独显使用教程，进行修改。装好系统进入后cpu架构三个问号。经过一番查阅，我最终修改成一图所示plist，依旧是无法驱动核显，架构显示3问号。

![image](https://user-images.githubusercontent.com/56849388/155250956-4f4cb860-e514-4c77-87a0-01de89a5f46b.png)

之后我的改动基于oc文档的coffee lake 部分内容，图二，改动了0700不work尝试0000。
![image](https://user-images.githubusercontent.com/56849388/155251114-ddd7e1c4-0f87-4242-ac50-f093772c2824.png)

问题依旧，再之后进了github 核显framebuffer，图三。
将devices id 改动为923E0000，系统为recovery在线安装的最新mor...

![image](https://user-images.githubusercontent.com/56849388/155251302-5c6a55b8-b808-4d5e-abca-43d810397c9a.png)

主要与教程的差异点是，devicesid 由9b3e0000，改动为923e0000
aapl 由07009b3e改为 00009b3e。
但无论何种情况，均无法驱动核显。

**Comment by GeQ1an** [comment]
> 如果你使用的是第 9 代 Coffee Lake Refresh 处理器，则需要为 iGPU 伪造 device-id 为 923E0000。 从 macOS 10.14.4 开始，不再需要伪造。

所以根本无需修改 device-id 为 923E0000，至于 AAPL,ig-platform-id，07009b3e 和 00009b3e 一般认为没有太大区别，所以这也不是影响你核显注入的问题所在。请检查 BIOS 里设置的集显共享显存是否为 64M。

**Comment by reyukari** [comment]
大佬你好，我已经按照您的说法将plist改回。
但是问题依旧，igpu信息显示不正常并且卡卡的，架构也还是三问号。

图1，2是hackintool打印的信息。

![image](https://user-images.githubusercontent.com/56849388/155452098-4ab21d4a-348f-4dda-b75d-b795988e0b9b.png)

![image](https://user-images.githubusercontent.com/56849388/155452119-7c9069eb-53b9-41e6-b46d-547320ce9b56.png)

图3，4是核显及bios版本的信息。

![image](https://user-images.githubusercontent.com/56849388/155452169-c6801881-e8b0-4850-890c-6e813656b513.jpeg)

![image](https://user-images.githubusercontent.com/56849388/155452191-8a39c407-3815-4bf0-bdaa-6d06580887f2.jpeg)

**Comment by GeQ1an** [comment]
问题解决了？我搜索和讨论了许久都没有结果。

**Comment by reyukari** [comment]
可以算是解决了，我解决了产生问题的源头，换了12代的设备，配上了nv的显卡，已经无法再黑果了。

**Comment by GeQ1an** [comment]
> 可以算是解决了，我解决了产生问题的源头，换了12代的设备，配上了nv的显卡，已经无法再黑果了。

确实是解决了。😅
