### ISSUE TITLE
升级1月23日版本后USB3.0失效

### ISSUE THREAD

**Issue by BlackLIHei** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#155]
大佬，升级1月23日版本后USB3.0失效，有没有解决办法？

**Comment by GeQ1an** [comment]
暂未收到其他用户的有关反馈，经过测试没有问题才上传了新的 USB 定制文件，有问题可先使用原来的定制，我也会继续测试排查问题。

**Comment by BlackLIHei** [comment]
解决了，禁用USBInjectAll.kext，启用USBMap.kext就搞定了。
谢谢大佬。
