### ISSUE TITLE
死活安装不上

### ISSUE THREAD

**Issue by Utmostmao** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#16]
微星b360m迫击炮
cpu：           9600k
内存：   阿斯加特8g
硬盘：   阿斯加特m2

问题：com.apple.xpc.launchd [1]

**Comment by Utmostmao** [comment]
大哥指点指点，我不知道问题出在哪，我用过小兵自带的efi，也试过几个同主板的，有些提示com.apple.xpc.launchd
有些    applenvme assert failed

**Comment by Utmostmao** [comment]
装上了，cpu-s测试变频只有三个档位

**Comment by Utmostmao** [comment]
哥，回复一下呗

**Comment by GeQ1an** [comment]
看一下 CPU-S 最新版本的更新时间，不适用于现在。

**Comment by Utmostmao** [comment]
原来是这样，我没有独显用iMac19.1会有什么问题不，不想用Macmini8.1

**Comment by GeQ1an** [comment]
> 原来是这样，我没有独显用iMac19.1会有什么问题不，不想用Macmini8.1

不可以，必须拥有独显。

**Comment by Utmostmao** [comment]
OK，谢谢

**Comment by Utmostmao** [comment]
哥，今天睡眠唤醒后自动重启了，一般在唤醒几秒后

**Comment by GeQ1an** [comment]
> 哥，今天睡眠唤醒后自动重启了，一般在唤醒几秒后

Emmm...... 黑苹果的睡眠/唤醒问题往往过于复杂，无法直接判断问题所在，如果没有定制 USB 的话，建议定制下 USB，可解决大部分睡眠/唤醒问题。

**Comment by Utmostmao** [comment]
我找到问题所在了，是声卡驱动，现在已解决，谢谢大佬

**Comment by Guiee** [comment]
> 我找到问题所在了，是声卡驱动，现在已解决，谢谢大佬

怎么解决的？可以帮助下我吗？

**Comment by Utmostmao** [comment]
config文件中的PowerTimeoutKernelPanic设置为yes/true

**Comment by Utmostmao** [comment]
> > 我找到问题所在了，是声卡驱动，现在已解决，谢谢大佬
> 
> 怎么解决的？可以帮助下我吗？

**Comment by Utmostmao** [comment]
> > 我找到问题所在了，是声卡驱动，现在已解决，谢谢大佬
> 
> 怎么解决的？可以帮助下我吗？

config文件中的PowerTimeoutKernelPanic设置为yes/true
