### ISSUE TITLE
有没有人尝试过用这个EFI引导安装12.2.1的呀

### ISSUE THREAD

**Issue by guange2015** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#161]
方法用的是下载升级包进入引导的方案，安装过程中一直弹出更新失败对话框，确定就退出安装。
也测试了用小兵的dmg刻盘，拨掉网线之类，都会报这个错误

注以前用这个efi一直是完美的，这次有点问题抹盘重装。

**Comment by GeQ1an** [comment]
12.2.1 发布当天已正常更新，最新的 EFI 支持 12.2.1 系统，更新失败可能由其他原因导致，macOS 并非不会出现问题。

**Comment by guange2015** [comment]
这个更新失败不是升级那种，而是在抹盘重装的过程中报更新失败

**Comment by guange2015** [comment]
目前进度，我怀疑是不是硬盘坏了，正在联系京东售后更换

**Comment by guange2015** [comment]
终于换了个新硬盘，直接opencore在线安装，一点问题都没有
