### ISSUE TITLE
 我发现，就算BIOS保持默认，也是可以引导并正常使用

### ISSUE THREAD

**Issue by geekbb** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#162]
所以为什么要推荐设置BIOS那个选项呢？

**Comment by GeQ1an** [comment]
你确定吗？拔掉主机所有线缆（包括显示器）、拆下主板电池 10 分钟以上，装上电池重新连接电缆，开机试一下能否正常开机、能否正常睡眠。

**Comment by geekbb** [comment]
> 你确定吗？拔掉主机所有线缆（包括显示器）、拆下主板电池 10 分钟以上，装上电池重新连接线缆，开机试一下能否正常启动 macOS。

是的，可以正常启动，因为我的显示器坏了，7天没有用电脑，今天显示器到了，我把主板BIOS重置了，然后又降级到7B23v19，什么都没调，可以正常使用

**Comment by GeQ1an** [comment]
> > 你确定吗？拔掉主机所有线缆（包括显示器）、拆下主板电池 10 分钟以上，装上电池重新连接线缆，开机试一下能否正常启动 macOS。
> 
> 是的，可以正常启动，因为我的显示器坏了，7天没有用电脑，今天显示器到了，我把主板BIOS重置了，然后又降级到7B23v19，什么都没调，可以正常使用

好的，那就正常用。总之这么设置可以减少绝大部分问题的发生，如果你不设置也能正常用，那自然是没有问题的。
