### ISSUE TITLE
请问引导后进入系统不跑代码直接卡在读条怎么解决？

### ISSUE THREAD

**Issue by IMWANGWEI** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#163]
配置和你一样，我是核显。根据你的教程修改替换EFI后进入没有跑代码直接卡在苹果读条界面。

**Comment by GeQ1an** [comment]
你加个 -v 看代码。

**Comment by IMWANGWEI** [comment]
加上去后 显示 IONVMeController

**Comment by GeQ1an** [comment]
> 加上去后 显示 IONVMeController

什么硬盘？

**Comment by IMWANGWEI** [comment]
凯侠rc10,应该和硬盘没关系啊，黑果小兵的EFI我能进去，就是太卡了

**Comment by GeQ1an** [comment]
> 凯侠rc10,应该和硬盘没关系啊，黑果小兵的EFI我能进去，就是太卡了

那再根据无独显使用部分检查一下核显注入部分吧，目前 EFI 没大问题，正常不会出现无法进入系统的问题。

**Comment by IMWANGWEI** [comment]
重新下载了然后重新按照只有核显的配置去更改了，现在情况是跑完代码黑屏（无信号）T T

**Comment by GeQ1an** [comment]
> 重新下载了然后重新按照只有核显的配置去更改了，现在情况是跑完代码黑屏（无信号）T T

添加 agdpmod=pikera 启动参数试一下，部分机器仅使用核显也需要这个启动参数。

**Comment by IMWANGWEI** [comment]
大佬，现在基本确定是 DeviceProperties > Add > PciRoot(0x0)/Pci(0x2,0x0) 的问题，我把这个改成和黑果小兵EFI一样就能正常进入系统，所以现在是要解决核显驱动问题吗？

**Comment by GeQ1an** [comment]
> 大佬，现在基本确定是 DeviceProperties > Add > PciRoot(0x0)/Pci(0x2,0x0) 的问题，我把这个改成和黑果小兵EFI一样就能正常进入系统，所以现在是要解决核显驱动问题吗？

意思是核显驱动注入 07009b3e 就无法正常启动，这个问题我最近听到了几例，都是只有核显、注入核显代码就不能正常开机，不正确注入反倒可以。这一情况在之前是几乎没发生过的。

**Comment by IMWANGWEI** [comment]
破案了，好像“添加 agdpmod=pikera”之后dp可以正常显示了，由于我另外一个显示器是VGA的，只能HDMI转VGA，我尝试下修改端口看HDMI能否正常输出。

**Comment by IMWANGWEI** [comment]
更正：大佬的efi没有问题，是因为默认是dp接口输出，所以像我这种比较旧的显示器不能正确输出信号，阅读opencore官方文档后在PciRoot(0x0)/Pci(0x2,0x0)处添加以下可以正常启动了，感谢大佬的对小白不懈的答疑！！

framebuffer-patch-enable | Data | `01000000`
framebuffer-con0-enable  | Data | `01000000`
framebuffer-con1-enable  | Data | `01000000`
framebuffer-con2-enable  | Data | `01000000`
framebuffer-con0-alldata | Data | `01010900 00080000 C7030000`
framebuffer-con1-alldata | Data | `02000A00 00040000 C7030000`
framebuffer-con2-alldata | Data | `03000800 00040000 C7030000`
