### ISSUE TITLE
OC从0.5.9升级到0.7.9，MinDate 和 MinVersion已设为-1，无法启动Catalina

### ISSUE THREAD

**Issue by xuconnery** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#165]
现在：OC为0.5.9，系统版本为10.15.5
硬件基本与Ge大同：i5-9600K+B360M+迪兰RX 570 4GB
期望：升级OC后，升级系统到最新12.3 Monterey

将Ge大最新的EFI文件（OC0.7.9）的三码修改成自己的，其他改动仅ShowPicker置为YES，MinDate 和 MinVersion已设为-1。

保存后通过USB启动引导，无法进入现有系统Catalina。

具体现象为：OC引导处选择macOS进入，显示苹果启动条，黑屏一下，再显示苹果启动条（苹果界面会比刚才小），然后进入macOS实用工具，四个选项：时间机器恢复、重新安装macOS、获得在线帮助、磁盘工具。

**Comment by xuconnery** [comment]
@GeQ1an 请Ge大帮忙看看

**Comment by GeQ1an** [comment]
1. 重置一下 NVRAM 试试
2. 不行的话，将 Misc > Security > SecureBootModel 设置为 Disabled

**Comment by xuconnery** [comment]
> 

谢谢Ge大，1和2都做了后，顺利引导成功。那么我更新系统后，还需要把SecureBootModel改回去嘛

**Comment by GeQ1an** [comment]
都可以。
