### ISSUE TITLE
一块硬盘装双系统，升级BIOS后，无法从OC引导，默认启动Windows

### ISSUE THREAD

**Issue by xuconnery** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#166]
原：OC为0.5.9，系统版本为10.15.5
硬件基本与Ge大同：i5-9600K+B360M+迪兰RX 570 4GB
期望：升级OC到0.7.9，升级系统到最新12.3 Monterey

在升级OC和系统的过程中，为了排除是BIOS的问题（具体见  https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI/issues/165   ），将BIOS升级到了最新的7B23v1C2(Beta version)。

然后发现：
BIOS - 启动 - UEFI硬盘BBS优先权 - 启动选项只有：Windows Boot Manager 和 禁止

启动顺序，选择UEFI Hard Disk的情况，上述选项：

如果选择Windows Boot Manager，开机启动会默认启动Windows系统
如果选择禁止，则开机进入不了任何系统，直接到BIOS界面

感觉OC的引导好像失效了一样。

我现在只能从U盘的OC进入macOS，而硬盘里的EFI分区和U盘的EFI是完全一样的。

**Comment by xuconnery** [comment]
请教 @GeQ1an 大佬，这个怎么修复啊

**Comment by GeQ1an** [comment]
其实就是双系统下重置 NVRAM 后，需要重建一下 OpenCore 引导。
