### ISSUE TITLE
完美安装！i5 8400+B360迫击炮+RX580 感谢大佬

### ISSUE THREAD

**Issue by fomoesc** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#17]
i5 8400+B360迫击炮+RX580
紫光p100 512G 装黑果
从盘pm981 256G装win10
一路顺利，完美！之前用了好几个clover的efi各种安装失败，不是cause 5就是斜杠禁止符
感谢大佬的奉献

**Comment by GeQ1an** [comment]
不客气。

**Comment by ghost-yuanye** [comment]
楼主可以提供一下您的EFI么？我的配置和您的一样~

**Comment by ylen0l** [comment]
楼主可以提供一下您的EFI么？我的配置和您的一样~
