### ISSUE TITLE
哥们问个关于USB定制的问题

### ISSUE THREAD

**Issue by tommywhl** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#18]
我看见你usb定制文件里有两个typeC+sw。
这两个是指主板上哪两个口，迫击炮背面不是只有一个typec么。
选项里typeC和typeC sw什么区别，也就是为什么要选typec sw。
望解惑 谢谢了

**Comment by tommywhl** [comment]
另外一个唤醒的问题 我的蓝牙键盘无法唤醒 ，鼠标唤醒是正常，是键盘自身不支持的原因吗？

**Comment by GeQ1an** [comment]
TypeC SW 用来表示区分正反的 Type-C 接口，每个 USB 3 以上的物理接口在定制 USB 时都需要有两个接口，一个 USB 3.0，一个 USB 2.0，否则无法使用缺失接口类型的 USB 设备。

**Comment by GeQ1an** [comment]
> 另外一个唤醒的问题 我的蓝牙键盘无法唤醒 ，鼠标唤醒是正常，是键盘自身不支持的原因吗？

不太清楚，没有试过用蓝牙设备唤醒。可能睡眠时机器关闭了蓝牙，导致无法通信，也可能是主板（或 BIOS 设置）不支持蓝牙唤醒。
建议先查看 BIOS 设置，尝试打开唤醒位置的一些设置项。

**Comment by tommywhl** [comment]
蓝牙不能唤醒基本上判断出来了 我手上这块94360cd 供电走的pcie上的3.3 没走usb的5v 所以睡眠时 卡是断电的。悲剧的是我一顿骚操作 这卡的蓝牙似乎坏了无线网卡正常 又是200多软妹币：（

**Comment by tommywhl** [comment]
蓝牙走的usb通道 蓝牙唤醒本质上还是usb唤醒 只不过手上这卡睡眠时断电的 usb只走了tx和rx 供电没走

**Comment by Utmostmao** [comment]
我早上才弄好的，连学带做20分钟搞掂[超详细](https://sleele.com/2019/06/07/%e4%bd%bf%e7%94%a8hackintool%e5%ae%9a%e5%88%b6%e9%bb%91%e8%8b%b9%e6%9e%9cusb%e9%a9%b1%e5%8a%a8/)
