### ISSUE TITLE
10.15.4换OC无法启动

### ISSUE THREAD

**Issue by scyehan** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#181]
你好，我是非钛金版，原来通过Clover启动，系统是10.15.4，现在睡眠有点问题，想换你这个
![image](https://user-images.githubusercontent.com/2596122/182860123-47c8b625-0ebc-4915-8fbc-0a8611a6427e.png)
BOOT目录也换成你这边提供的BOOTx64.efi
![image](https://user-images.githubusercontent.com/2596122/182860545-39c8a1af-159c-496b-938f-56e5e51db0e8.png)
OC目录是你这边下载的，我是无核心，相应的三码和rom也配置了，Add那条删了，第10点catalina那两个值也改成了-1
现在重启选原来UEFI这个启动项，直接没反应，从我另一块硬盘启了windows，请问该如何排查

**Comment by scyehan** [comment]
似乎感觉不是没清理，因为开机OC的选操作系统的画面都没出来，就直接进了windows，感觉都还没引导到Mac OS

**Comment by GeQ1an** [comment]
1. 修改配置文件 Misc > Boot > ShowPicker 为 true。
2. 使用 PE 系统的 UEFI 启动项管理，查看是否有 OC 启动项，没有的话手动添加，须指定为 BOOTx64.efi

**Comment by scyehan** [comment]
就是这个问题，默认启动项是windows，多谢
