### ISSUE TITLE
不知道为什么蓝牙能识别却无法开启

### ISSUE THREAD

**Issue by YaoShuwei** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#186]
![image](https://user-images.githubusercontent.com/17966298/199451091-0faea743-102f-43c5-bc64-eefbea468bfd.png)

蓝牙是网卡带的，插在HS01上，显示unknown，而且在windows上也无法开启。
在没装显卡前，网卡是插在pcie3上的，蓝牙一直稳定使用，但是显卡挡到了pcie2和3，pcie4又和m.2冲突，只好买了根pcie延长线，此后蓝牙就不稳定了，现在怀疑是延长线导致的蓝牙只能识别到但是无法开启，不知道有没有人遇到过这种情况，要如何解决？
![image](https://user-images.githubusercontent.com/17966298/199451121-a0208ab8-ea05-41e0-8d6f-9e65b1b1b52a.png)

![image](https://user-images.githubusercontent.com/17966298/199452467-a468b15b-509d-40de-8d9f-08f3458c3658.png)

**Comment by GeQ1an** [comment]
蓝牙走的是 USB 通道，使用 PCI-E 延长线理论上不会受影响，请尝试完全断电后再开机尝试。
