### ISSUE TITLE
9400的变频

### ISSUE THREAD

**Issue by liujinjiao** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#19]
改掉10、11的hwp变频，9400的变频还能用吗？谢谢楼主

**Comment by Utmostmao** [comment]
自己定制[4.1章节](https://blog.xjn819.com/?author=1)

**Comment by GeQ1an** [comment]
好像你有在 telegram 上问我？

系统自身有 HWP 变频，但苹果出于散热考虑，往往比较保守，还是建议自己定制一下 HWP 变频。

**Comment by liujinjiao** [comment]
对的是我问的，太感谢您了
