### ISSUE TITLE
windows时间差八小时

### ISSUE THREAD

**Issue by scyehan** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#191]
请问相同机器windows时间会差八小时要怎么解

**Comment by ChanXiaoKing** [comment]
请问您解决了吗 我也遇到了相同的问题

**Comment by ChanXiaoKing** [comment]
我也遇到了相同的问题，我的解决方法是与时间服务器同步

**Comment by GeQ1an** [comment]
在 Windows 中使用管理员身份进入 CMD 执行以下命令即可。
`Reg add HKLM\SYSTEM\CurrentControlSet\Control\TimeZoneInformation /v RealTimeIsUniversal /t REG_DWORD /d 1`
