### ISSUE TITLE
MacOS写入U盘，重启电脑选择U盘启动后就一直黑屏是怎么回事？

### ISSUE THREAD

**Issue by iwsbiwy** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#193]
安装MacOS13.2，配置是I7-8700+B360迫击炮+RX560D 4G，也按说明文件的内容更改了BIOS设置。
[![p9KKuGR.png](https://s1.ax1x.com/2023/04/26/p9KKuGR.png)](https://imgse.com/i/p9KKuGR)
[![p9KKKR1.png](https://s1.ax1x.com/2023/04/26/p9KKKR1.png)](https://imgse.com/i/p9KKKR1)

**Comment by natpacket** [comment]
我和你一样 ，你现在解决了么

**Comment by daoye** [comment]
一样的问题，我是8700，没有独显.

**Comment by daoye** [comment]
> 一样的问题，我是8700，没有独显.

我换了最新版本的opencore 和 相关驱动，可以解决此黑屏问题。

**Comment by GeQ1an** [comment]
如果问题发生在首次安装 macOS，可在配置文件里开启 ShowPicker，应该可以解决黑屏的问题。
