### ISSUE TITLE
Unfortunately, I did not find the BIOS update for the MSI b360 Mortar version 7B23v16.

### ISSUE THREAD

**Issue by AliMosbah** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#194]
Unfortunately, I did not find the BIOS update for the MSI b360 Mortar version 7B23v16 on the official website: 
https://www.msi.com/Motherboard/B360M-MORTAR/support
Does it work on version 7B23v17 without any problems? 
These are my device specifications :
MSI B360 Mortar
CPU i5-8400
GPU MSI RX 580 8g OC 
RAM Adata 2x8 2666 MHz
SSD Adata Ligends 710 500GB NVMe 
Does this EFI file work without any problems, or does it require a modification other than a modification to the serial number?

**Comment by GeQ1an** [comment]
After testing, versions 7B23v16 to 7B23v19 can be used, and 7B23v17 can be used naturally. If you use both integrated graphics and discrete graphics, after setting the BIOS, you can directly fill in the serial number and other information to use it.
