### ISSUE TITLE
能出一个单独核显的EFI吗？我按照提示修改单独核显的EFI总是卡苹果图标。

### ISSUE THREAD

**Issue by sducstriker** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#198]
如题，非常感谢！

**Comment by cmj799** [comment]
我的也是出现这种问题，然后我搜集了其他的单核显config文件，对比发现了是缓冲帧补丁的问题。我在打上缓冲帧补丁后，在logo进度三分之一处加载显卡时，会稍微花屏一下，然后黑屏两三下就继续读进度，顺利进入系统。此前没有打补丁的时候，-v参数下，跑完码电脑直接显示屏无连接，去掉-v参数下，电脑在苹果logo界面进度条三分之一处断开显示屏连接。我在稍晚些会把我自己用的efi上传。目前我的efi文件的睡眠唤醒还是有问题，限于水平有限，我也还是希望原作者能够做出更好的单核显efi。

**Comment by sducstriker** [comment]
> 单核显测试没问题，请参考 [无独显使用](https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#%E6%97%A0%E7%8B%AC%E6%98%BE%E4%BD%BF%E7%94%A8) 修改，尤其是核显设备参数的位置。
![image](https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI/assets/60010676/436212fd-f803-4b55-8d53-ef1f10d1091b)
![image](https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI/assets/60010676/d0235f77-610f-4f63-9b97-d10c0166ef07)
这样修改没问题吧？

**Comment by sducstriker** [comment]
如果可以的话，还是请大佬把测试核显的config发一份吧

**Comment by Went1ng** [comment]
21年的 还是bigsur 
![image](https://user-images.githubusercontent.com/67221893/258689713-44726e72-229d-4e58-a90b-9cf64dd6a4b2.jpeg)

**Comment by sducstriker** [comment]
> 21年的 还是bigsur ![image](https://user-images.githubusercontent.com/67221893/258689713-44726e72-229d-4e58-a90b-9cf64dd6a4b2.jpeg)

谢谢 我打算升级13

**Comment by Went1ng** [comment]
修改核显参数基本不影响，直接替换文件可能无法进入系统（我也没发文件）

**Comment by GeQ1an** [comment]
> 修改核显参数基本不影响，直接替换文件可能无法进入系统（我也没发文件）

Bingo! 一般核显参数不会卡 logo，很可能是 BIOS 设置问题。

**Comment by sducstriker** [comment]
> > 修改核显参数基本不影响，直接替换文件可能无法进入系统（我也没发文件）
> 
> Bingo! 一般核显参数不会卡 logo，很可能是 BIOS 设置问题。

一语惊醒梦中人呐，前些日子主板掉电了！检查bios去

**Comment by sducstriker** [comment]
> > 修改核显参数基本不影响，直接替换文件可能无法进入系统（我也没发文件）
> 
> Bingo! 一般核显参数不会卡 logo，很可能是 BIOS 设置问题。

确实是bios的锅，感谢大佬指点。顺便说一下，关于无核显三分之一进度黑屏或者出现五国的问题，可以尝试修改bios-setting-内建显示配置 设置第一显卡【igp】共享内存64M。
