### ISSUE TITLE
从bigsur就开始用你这个efi了，但是单独显硬解的功能始终没搞定，还是自己研究出来的

### ISSUE THREAD

**Issue by spldmanager** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#199]
我的机型是b365微星+9400f+rx570，用了你这个efi好多个版本了，其他功能都好就这个硬解从来没成功过
跟选择什么macpro、iMac机型根本没关系，主要是你的config里面没有注入pci设备信息
通过hackintool可以查看到显卡，但是vda解码器就是无法解码，实际上要解决很简单，就是用opencore configuration，在设备属性设置里面，把vga的pci显卡设备添加进去，然后正确设置好显卡的名称就可以了
现在vda解码器显示完全支持，videoproc也能正常检测到硬解了

2年多了吧，这个硬解的问题就困扰了我，显卡识别但是无法硬解，cpu占用始终在20%以上，编辑ppt都一卡一卡的，甚至于我都想直接换白苹果了
我不知道这个是我自己特殊的问题，还是作者真的没做好这一点，可能我真的不能只做伸手党，还得自己研究

**Comment by GeQ1an** [comment]
好的，很有想法和动手能力。没条件测试只有独显的环境，后面有问题的朋友可以参考解决。

**Comment by berlinway** [comment]
找到解决方案了，贴个图 记录一下 

https://www.shuihuoibm.com/thread-582315-1-1.html

![image](https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI/assets/45029945/6b37439a-9884-4b4c-bf19-19ca92f7a67b)
