### ISSUE TITLE
能否上传到release界面

### ISSUE THREAD

**Issue by pfjmqbrkfh** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#2]
能否上传efi到release界面，我从clone download界面下载下来开机有错误。

**Comment by GeQ1an** [comment]
理论上不该有问题的，可以详细描述一下错误吗？是第一次从 OC 启动？

**Comment by pfjmqbrkfh** [comment]
你好，我是从tonymoses的贴子下载的efi，改了三码，启动正常，不过有几次突然自动重启的现象，我想换成你的efi，按照你的贴子改完之后，启动出现错误，我是刚接触黑苹果，还不是很精通，想再下载一下改一遍试试看。
![IMG_4134](https://user-images.githubusercontent.com/30342141/71819704-a9959880-30c7-11ea-90a7-34bf39deb489.JPG)

**Comment by pfjmqbrkfh** [comment]
oc:nested rerun is not supported
bs:failed to start opencore image-already started
bs:failed to load opencore from disk-already started
oc:boot failed- not found
ocb:startimage failed-not found
halting on critical error

这是开机出现的错误

**Comment by GeQ1an** [comment]
我觉得可能是你 EFI 文件夹的放置有问题吧，看 Nested ReRun 错误像是从 OC 里 启动 OC？
你先排查一下，是不是把整个 EFI 文件夹放入到了 EFI 分区（需要先备份后删除其他 EFI），如果还有问题的话，请在 [Telegram](https://t.me/GeQ1an) 联系我，我愿和你一起排除问题（因为我也是黑果小白）。
