### ISSUE TITLE
如何设置才能正常进入 OC 的选择界面？

### ISSUE THREAD

**Issue by derbalkon** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#21]
看指南上说是按住 Esc/Option 都可以进入，但是在我这里按住直接就进入系统了不出现选择界面，只有很快速地连按才能进入选择界面，我的 TakeoffDelay 从 2000 到 75000 都试过，依旧不能通过按住 Esc/Option 进入选择界面，这个是和输入设备有关吗？我的设备是 B360M + IKBC C87。

**Comment by JokerMas** [comment]
就只是按一下吧

**Comment by derbalkon** [comment]
> 就只是按一下吧

只是按一下的话，有很大几率是进不去的，因为你并不知道你按的时候 OC 是否在加载。

**Comment by GeQ1an** [comment]
说实话这个确实比较迷，有些时候长按可以进入（大概率不行），所以我一般也是快速连按。

P.S. 可能真的和键盘有关。

**Comment by JokerMas** [comment]
> > 就只是按一下吧
> 
> 只是按一下的话，有很大几率是进不去的，因为你并不知道你按的时候 OC 是否在加载。

出现主板logo的时候按一下，可以的

**Comment by derbalkon** [comment]
update:

最近经过几天试验发现，我好像找到了无法长按呼出 OC 选单的方法，不知道这种方法是不是放诸四海皆准：
1. 首先在 BIOS 中打开 MSI 快速启动；
2. 设法进入 OC 选单后，在选单中使用 `Ctrl`+`Enter` 设定 macOS 为默认启动项，进入 macOS 之后再重启；
3. 启动时长按 `Alt` 之后选单就神奇地出现了。

**什么不会导致呼出选单失效**：在选单中使用 `Ctrl`+`Enter`，或者从 macOS 中的启动磁盘设置 Windows 为默认启动项。
**什么会导致呼出选单失效**：一旦某天进入 BIOS 再重启的话，长按呼出选单的行为就失效了，还要按上面的步骤再做一次。

所以看起来，似乎微星的 BIOS 或者 BIOS UEFI 选单之类的东西，在启动时会跟 OC 有某些冲突，包括之前有过[开机按 F11 卡在黑屏不能进入 BIOS](https://github.com/SuperNG6/MSI-B360-Catalina-EFI/issues/152) 的经历，让我更加怀疑这一点了。

上面的步骤我重复试验了很多次，屡试不爽，config 里的 TakeoffDelay 我甚至可以直接设置为 0，但是我也不确定是不是每个人都可以这样实现……

虽然官方不推荐把快速启动打开，但是如果 Windows 下的快速启动是关闭的话，似乎打开也没有什么大问题。尽管打开快速启动之后不识别 USB 等设备会导致不能通过 F11 进入 BIOS，但是在 BIOS 里打开 GO2BIOS 后可以长按开机键直达 BIOS，又或者从 Windows 按 `Shift` + 重启选择进入 BIOS，我感觉也不是无法接受。这样一来就意味着，你得用 OC 去引导 Windows 和 U 盘了，既然 SSDT 都已经做了系统判断了，目前看来引导上也没有什么问题，只不过如果 config 里的 UUID 填的不是主板自身的 UUID 的话，Windows 恐怕还要重新激活，如果不介意的话可以一试。
