### ISSUE TITLE
usb速度

### ISSUE THREAD

**Issue by liujinjiao** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#23]
替换USBport.kext并启用后恢复正常
链接: https://pan.baidu.com/s/1NlWUaXe9hAc747TLFuywng  密码: 6aa4

**Comment by liujinjiao** [comment]
好像还是不行，，读取很快，写入慢

**Comment by GeQ1an** [comment]
我这里 USB 速度是正常的。
