### ISSUE TITLE
核显用Intel Power Gadget测试好像没有驱动

### ISSUE THREAD

**Issue by liujinjiao** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#24]

**Comment by GeQ1an** [comment]
下载一个 HEVC 的视频打开测试。

**Comment by liujinjiao** [comment]
我的会限制在0.35好像换了魔改的WhateverGreen.kext就跑1.2了

**Comment by GeQ1an** [comment]
> 我的会限制在0.35好像换了魔改的WhateverGreen.kext就跑1.2了

目前来说 WhateverGreen 确实是这样的，想要核显满速只能不使用或使用魔改版。不过 WeG 将在 1.3.8 版本支持 GuC Firmware 的载入，实现核显满速运行。
