### ISSUE TITLE
你好，OC 可以做双系统吗？ 网上教程也没成功的， 想做win10 ，我有两个M2 SSD ，可

### ISSUE THREAD

**Issue by nangsze** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#25]
你好，OC 可以做双系统吗？ 网上教程也没成功的， 想做win10 ，我有两个M2 SSD ，可以分开安装，向你请教。

**Comment by GeQ1an** [comment]
可以直接把 Windows 安装在另一块 SSD 里，电脑开机时按 F11 更换启动磁盘，即可启动对应的系统。

**Comment by nangsze** [comment]
好的谢谢大神呢。

**Comment by liujinjiao** [comment]
注意第四个pcle插口会和第二个ssd冲突

**Comment by liujinjiao** [comment]
微星B360M迫击炮会

**Comment by nangsze** [comment]
@liujinjiao  我又要退板了， B360 +RX590 我的无线黑苹果网卡接不了，显卡太大，无奈啊

**Comment by liujinjiao** [comment]
我的也是rx570，，可以考虑买个转接线，我刚买还没到

**Comment by nathan-code** [comment]
> @liujinjiao 我又要退板了， B360 +RX590 我的无线黑苹果网卡接不了，显卡太大，无奈啊

如果是迫击炮可以插显卡口啊，长的那个，长的兼容短的。

**Comment by nathan-code** [comment]
> 我的是rx570，也是装不下去，可以考虑买个转接线，我刚买还没到

我的显卡把两个短的PCIE槽挡了，也以为插不了，然后看到说长的PCIE槽兼容短的，插上后完美使用中。

**Comment by nangsze** [comment]
算了，退了，前面有人说第四个PCIE 和M2 SSD 有冲突，正好 我也是用两个M2的SSD

**Comment by nangsze** [comment]
> > 我的是rx570，也是装不下去，可以考虑买个转接线，我刚买还没到
> 
> 我的显卡把两个短的PCIE槽挡了，也以为插不了，然后看到说长的PCIE槽兼容短的，插上后完美使用中。

算了，退了，前面有人说第四个PCIE 和M2 SSD 有冲突，正好 我也是用两个M2的SSD

**Comment by jixiangqd** [comment]
用oc引导双系统也是可以的，目前测试没啥大问题，可以更新下配置，我前两天因为这个折腾了好久

**Comment by liujinjiao** [comment]
你的双系统是咋搞的
