### ISSUE TITLE
b360m和9600k超频问题，十分感谢

### ISSUE THREAD

**Issue by xu574** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#27]
博主，我想问一下，360迫击炮配置主板不是不可以超频吗，就是会不会性能损失呀，还有一个就是打算显卡用蓝宝石rx5500xt也可以直接用这个efi吧，十分感谢，十分感谢

**Comment by Utmostmao** [comment]
哇，我的梦想显卡啊

**Comment by xu574** [comment]
哈哈，应该是2080ti才对呀

**Comment by Utmostmao** [comment]
这个没法黑苹果

**Comment by xu574** [comment]
我感觉如果用i5 9700k搭配b360迫击炮，不超频就没啥问题，不太懂黑苹果超频问题，可能就没这个选项吧，，这样说的话360迫击炮搭配上i7 9700k不超频的话，按照这个u也能睿频到4.7/8/9吧，其实就是想用博主的efi哈哈

**Comment by xu574** [comment]
> 这个没法黑苹果
老哥，睡觉吧，两点了

**Comment by Utmostmao** [comment]
efi跟cpu没多大关系，主要是看主板

**Comment by xu574** [comment]
> efi跟cpu没多大关系，主要是看主板

对呀，我想换个i7 9700k，不过感觉和360迫击炮不太般配，虽然我记得有人测试过这两个是可以正常睿频到4.9，就是不超频就行了

**Comment by Utmostmao** [comment]
你干什么用？要上这么强的U

**Comment by Utmostmao** [comment]
要不就直接9900k+z390，爽爆

**Comment by xu574** [comment]
> 你干什么用？要上这么强的U

升级电脑了，以后pr和ps，正想装一个店电脑，又想更好兼容黑苹果，不行的话就用i5 9700,,其实还一个想法就是和白苹果MAC PRo最便宜的那套配置，八核心3.5GHZ的那个比比分，可能我是闲的慌

**Comment by xu574** [comment]
> 要不就直接9900k+z390，爽爆

是爽呀，不过可能我要自己写efi了

**Comment by Utmostmao** [comment]
放心吧，我看到最多就是390主板的EFI了

**Comment by xu574** [comment]
> 放心吧，我看到最多就是390主板的EFI了

嚯，可能我还没看到，我今天下午才刚开始看，明天我在看看，要睡了兄弟，告辞啦，明天我在回来

**Comment by GeQ1an** [comment]
> 博主，我想问一下，360迫击炮配置主板不是不可以超频吗，就是会不会性能损失呀，还有一个就是打算显卡用蓝宝石rx5500xt也可以直接用这个efi吧，十分感谢，十分感谢

虽然 b360m 没办法超频，但带 K 的 U 自身睿频也是比较高的，所以还是自己权衡吧。
