### ISSUE TITLE
opencore 无法引导

### ISSUE THREAD

**Issue by bowenqiang** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#28]
尝试用opencore引导安装黑苹果，bios里面按照说明配置了，引导的时候闪了一下直接提示“OCB: Failed to match a default boot option”，然后就启动了windows。通过拍视频截下了闪的一瞬间的屏幕：
![WeChat Image_20200403214520](https://user-images.githubusercontent.com/11279043/78368010-8d859280-75f5-11ea-8b44-1dad764261ef.jpg)

之后就是“OCB: Failed to match a default boot option”：
![WeChat Image_20200403214530](https://user-images.githubusercontent.com/11279043/78368062-9f673580-75f5-11ea-9d29-9578845f4578.jpg)

究竟是什么问题？

硬件：
MSI-B360M Mortar, I7 9700, AMD rx 5700.

**Comment by 44886** [comment]
我的也是相同问题

**Comment by bowenqiang** [comment]
> 我的也是相同问题
换了一个EFI就可以了（
https://github.com/ArchFeh/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI-without-core-graphic）
然后自己根据情况稍微改动了一些。

**Comment by bowenqiang** [comment]
发现用别的EFI完成全新安装后，在换回这个EFI是可以正常引导的，好像就是全新安装的时候有问题。
