### ISSUE TITLE
关于N卡的问题

### ISSUE THREAD

**Issue by marunrun** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#29]
你好，我电脑使用的Nvida 1050ti 显卡。
安装10.15版本无法安装显卡驱动，我尝试安装10.13.6版本。
但通过您的EFI无法正确从磁盘引导启动。
启动之后直接出现禁止图标，请问是我需要修改什么配置么

**Comment by run6** [comment]
This version of Mac OS  X is not supported on this platform 
Reason: Mac-AA95B1DDAB278b95

**Comment by run6** [comment]
修改机型 已解决

**Comment by nathan-code** [comment]
> 修改机型 已解决

改了哪个机型？

**Comment by GeQ1an** [comment]
> > 修改机型 已解决
> 
> 改了哪个机型？

支持 macOS High Sierra 10.13 的机型都行。

**Comment by run6** [comment]
> > 修改机型 已解决
> 
> 改了哪个机型？

IMac 18.2 18.3都可以的  只要是支持10.13的就可以 找跟自己配置最接近的
