### ISSUE TITLE
支持使用 Safari 观看 Netflix 吗？

### ISSUE THREAD

**Issue by derbalkon** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#3]
感觉黑果的 DRM 总有问题，看到 README 里说支持 Apple TV Plus，那么 Netflix 是不是也支持呢？

另外，如果使用 iMac19,2 的机型的话会不会有问题呀？

**Comment by GeQ1an** [comment]
目前可以完美观看 Apple TV Plus，通过 Safari 硬解观看 Netflix 理论上也是支持的，但目前部分显卡 (主要为 RX 560 / RX 570 / RX 580 / RX 590) 有兼容问题，会导致打开 Netflix 视频电脑卡死，等待 WhateverGreen 后续更新。
使用 iMac19,2 也没问题，但需要自己修改。

**Comment by derbalkon** [comment]
明白了！感谢！

**Comment by GeQ1an** [comment]
升级 macOS 10.15.4 后，RX 4XX/500 大部分显卡可正常通过 Safari 硬解观看 Netflix 等部分流媒体。

**Comment by derbalkon** [comment]
多谢提醒！升级之后打开 Netflix 已经不报错了，但是一直卡在缓冲阶段，是需要在 arg 加上 shikigva 相关的参数吗？

**Comment by GeQ1an** [comment]
shikigva=80
