### ISSUE TITLE
关于BIOS更改

### ISSUE THREAD

**Issue by healyoo** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#32]
您好！我的配置和你的一样，谢谢分享！
我现在配件到了，准备装机，请问下第一次安装进入的时候是否需要先设置BIOS，在安装系统呢？

**Comment by wcnvidia** [comment]
这是肯定的啊

**Comment by healyoo** [comment]
> 这是肯定的啊
大哥 能不能指导下我纯OC引导安装黑苹果怎么把EFI复制到电脑的硬盘里呀，以后不用优盘九能启动了。完成这个步骤还有什么其他的需要设置的吗（网上OC的资料比较少呀）

**Comment by wcnvidia** [comment]
> 这是肯定的啊
> 大哥 能不能指导下我纯OC引导安装黑苹果怎么把EFI复制到电脑的硬盘里呀，以后不用优盘九能启动了。完成这个步骤还有什么其他的需要设置的吗（网上OC的资料比较少呀）

你用最新版的clover configurator把U盘和自己的硬盘的EFI分区都挂载上，然后把U盘的EFI分区中的EFI目录复制进硬盘EFI分区的EFI目录，然后BIOS里面把第一启动项设置成UEFI OS:xxxxxxx就行了。

**Comment by healyoo** [comment]
谢谢！我现在设置BIOS好了，检查无错，选择U盘启动，但是进入不了OC引导，这是哪里的问题呀？是安装优盘没有弄好吗，但是它识别了啊。。

**Comment by healyoo** [comment]
> > 这是肯定的啊
> > 大哥 能不能指导下我纯OC引导安装黑苹果怎么把EFI复制到电脑的硬盘里呀，以后不用优盘九能启动了。完成这个步骤还有什么其他的需要设置的吗（网上OC的资料比较少呀）
> 
> 你用最新版的clover configurator把U盘和自己的硬盘的EFI分区都挂载上，然后把U盘的EFI分区中的EFI目录复制进硬盘EFI分区的EFI目录，然后BIOS里面把第一启动项设置成UEFI OS:xxxxxxx就行了。

谢谢！我现在设置BIOS好了，检查无错，选择U盘启动，但是进入不了OC引导，这是哪里的问题呀？是安装优盘没有弄好吗，但是它识别了啊。。

**Comment by Utmostmao** [comment]
> > > 这是肯定的啊
> > > 大哥 能不能指导下我纯OC引导安装黑苹果怎么把EFI复制到电脑的硬盘里呀，以后不用优盘九能启动了。完成这个步骤还有什么其他的需要设置的吗（网上OC的资料比较少呀）
> > 
> > 
> > 你用最新版的clover configurator把U盘和自己的硬盘的EFI分区都挂载上，然后把U盘的EFI分区中的EFI目录复制进硬盘EFI分区的EFI目录，然后BIOS里面把第一启动项设置成UEFI OS:xxxxxxx就行了。
> 
> 谢谢！我现在设置BIOS好了，检查无错，选择U盘启动，进入oc引导了。但是每次安装的时候都说安装不成功，需要重试，镜像我重新下了还是不行，这是怎么回事呀

要修改一下，让它显示OC引导界面，然后自己选择引导项。或者设置usb为第一启动，开机马上疯狂连按esc进入选择界面。（额外提醒：需要装Windows的话，最好先安装windows)

**Comment by Utmostmao** [comment]
> > > 这是肯定的啊
> > > 大哥 能不能指导下我纯OC引导安装黑苹果怎么把EFI复制到电脑的硬盘里呀，以后不用优盘九能启动了。完成这个步骤还有什么其他的需要设置的吗（网上OC的资料比较少呀）
> > 
> > 
> > 你用最新版的clover configurator把U盘和自己的硬盘的EFI分区都挂载上，然后把U盘的EFI分区中的EFI目录复制进硬盘EFI分区的EFI目录，然后BIOS里面把第一启动项设置成UEFI OS:xxxxxxx就行了。
> 
> 谢谢！我现在设置BIOS好了，检查无错，选择U盘启动，进入oc引导了。但是每次安装的时候都说安装不成功，需要重试，镜像我重新下了还是不行，这是怎么回事呀

你也可以选择先使用这个安装[https://github.com/Lubibest/MSI-B360M-MORTAR](url)

**Comment by healyoo** [comment]
> > > > 这是肯定的啊
> > > > 大哥 能不能指导下我纯OC引导安装黑苹果怎么把EFI复制到电脑的硬盘里呀，以后不用优盘九能启动了。完成这个步骤还有什么其他的需要设置的吗（网上OC的资料比较少呀）
> > > 
> > > 
> > > 你用最新版的clover configurator把U盘和自己的硬盘的EFI分区都挂载上，然后把U盘的EFI分区中的EFI目录复制进硬盘EFI分区的EFI目录，然后BIOS里面把第一启动项设置成UEFI OS:xxxxxxx就行了。
> > 
> > 
> > 谢谢！我现在设置BIOS好了，检查无错，选择U盘启动，进入oc引导了。但是每次安装的时候都说安装不成功，需要重试，镜像我重新下了还是不行，这是怎么回事呀
> 
> 要修改一下，让它显示OC引导界面，然后自己选择引导项。或者设置usb为第一启动，开机马上疯狂连按esc进入选择界面。（额外提醒：需要装Windows的话，最好先安装windows)

谢谢！可是有遇到了我问问题，在网上搜不到。系统安装好了，激活设置过程中无法使用键盘是怎么回事呀。。。

**Comment by Utmostmao** [comment]
> > > > > 这是肯定的啊
> > > > > 大哥 能不能指导下我纯OC引导安装黑苹果怎么把EFI复制到电脑的硬盘里呀，以后不用优盘九能启动了。完成这个步骤还有什么其他的需要设置的吗（网上OC的资料比较少呀）
> > > > 
> > > > 
> > > > 你用最新版的clover configurator把U盘和自己的硬盘的EFI分区都挂载上，然后把U盘的EFI分区中的EFI目录复制进硬盘EFI分区的EFI目录，然后BIOS里面把第一启动项设置成UEFI OS:xxxxxxx就行了。
> > > 
> > > 
> > > 谢谢！我现在设置BIOS好了，检查无错，选择U盘启动，进入oc引导了。但是每次安装的时候都说安装不成功，需要重试，镜像我重新下了还是不行，这是怎么回事呀
> > 
> > 
> > 要修改一下，让它显示OC引导界面，然后自己选择引导项。或者设置usb为第一启动，开机马上疯狂连按esc进入选择界面。（额外提醒：需要装Windows的话，最好先安装windows)
> 
> 谢谢！可是有遇到了我问问题，在网上搜不到。系统安装好了，激活设置过程中无法使用键盘是怎么回事呀。。。
把usbinjectall.kext开关打开，usbports.kext开关关闭，或者把鼠标键盘插口（usb2.0）

**Comment by healyoo** [comment]
@Utmostmao 嗯嗯 或者或者把鼠标键盘插口（usb2.0）指的是把键盘插在USB2.0的接口上吗？

**Comment by healyoo** [comment]
@Utmostmao  无语了…我现在一直按esc 也没用了，直接进入激活程序…关键是键盘也不能用！换了efi也不行 这可怎么办呢？
