### ISSUE TITLE
更新OC0.5.7后无法正常睡眠

### ISSUE THREAD

**Issue by JokerMas** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#35]
点击睡眠后，usb键盘、鼠标及显示器可以断电，然后仅此而已，风扇显卡一直没断电。而且，无法通过任何方式唤醒，只能强制关机。
是配置文件哪里需要更新，还是OC的问题？

**Comment by JokerMas** [comment]
确认原因：cpufriend的锅。禁用即可。

**Comment by Heelc** [comment]
> 确认原因：cpufriend的锅。禁用即可。

我遇到了和你一样问题，请问是直接修改EFI中config.plist的Kernel->Add->cpufriend的enabled改为false，然后重启系统就行了吗？

**Comment by DrKoschei** [comment]
> > 确认原因：cpufriend的锅。禁用即可。
> 
> 我遇到了和你一样问题，请问是直接修改EFI中config.plist的Kernel->Add->cpufriend的enabled改为false，然后重启系统就行了吗？

我是这样解决的

**Comment by nptry** [comment]
> 确认原因：cpufriend的锅。禁用即可。

我的现象和楼主一致，禁用后确实解决了此问题，产生了新的问题是睡眠后主机秒醒（显示器未亮，键盘按键正常亮起）。现在去解决秒醒的问题了😊

**Comment by SkyGrass** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
