### ISSUE TITLE
请问，作者是否遇到过无故重启的情况，panic之类的？

### ISSUE THREAD

**Issue by i0Ek3** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#38]
如题，楼主本人的机器最近几周出了很多次无故重启的问题，大部分是我在删除虚拟机中的快照时出现的，先是卡住不动，然后重启。[跟SuperNG6讨论了几次，基本上认定是SSD的问题](https://github.com/SuperNG6/MSI-B360-Catalina-EFI/issues/157)，不知道作者这边是否有过重启的情况？因为我的机器大部分配置和你的一致，除了CPU和SSD以外，当然我的没有独立显卡。

**Comment by GeQ1an** [comment]
目前为止，我没有遇到过无故重启的情况，甚至除了之前 DRM 问题冻屏强制重启外，没有遇到过非正常关机、重启的情况。

**Comment by i0Ek3** [comment]
@GeQ1an 好的，非常感谢反馈，看来SSD是要升级为一些高品质的才行。
