### ISSUE TITLE
有关不同CPU和同一主板的帮助

### ISSUE THREAD

**Issue by ahadrox** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#39]
嗨，我有i3 9100F和RX 5500 XT GPU，以及相同的主板MSI B360M迫击炮。 我可以直接使用您的EFI还是必须手动进行SSDT？

**Comment by GeQ1an** [comment]
参考 “无核显使用” 修改即可。

**Comment by ahadrox** [comment]
谢谢，我的朋友。 上帝祝福你。
