### ISSUE TITLE
如果想要沿用三码，应该用哪个 UUID？

### ISSUE THREAD

**Issue by derbalkon** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#4]
> 如果之前在 Clover 时就使用 iMac19,1 机型，可直接使用之前的三码，或使用 Clover Configurator （其他工具亦可）选择 iMac19,1 机型生成新的三码 + ROM，用 ProperTree 打开 EFI/OC/config.plist 文件，填入到……

请问如果想要沿用之前的三码，OC → config.plist → Gerneric 里所指的 SystemUUID 就是 Clover 里的 SmUUID 吗？因为用 acidanthera 的 macserial 查到的 SystemUUID 是「关于本机」里的「硬件 UUID」，而这 UUID 跟 Clover 里的 SmUUID 是不同的，很让人头大……

**Comment by GeQ1an** [comment]
不要怀疑，OC → config.plist → Gerneric 里所指的 SystemUUID 就是 Clover 里的 SmUUID.
![](https://blog.xjn819.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-09-at-4.40.19-PM.png)
