### ISSUE TITLE
关机后鼠标不断电（灯亮）

### ISSUE THREAD

**Issue by TYan917** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#41]
处理器是：i5 9400F
主板：B360M 迫击炮
鼠标：雷蛇蝰蛇标准版
使用驱动为：USBPower.kext（config.plist已经启动USBPower驱动）
根据使用描述内将USB驱动内机器型号改为iMac Pro 1，1。发现关机后鼠标不断电，指示灯还持续亮，重新插拔后不亮。睡眠正常。
还请大神帮忙找下原因，谢谢！

**Comment by GeQ1an** [comment]
是关机后鼠标还在亮？睡眠时呢？

**Comment by TYan917** [comment]
> 是关机后鼠标还在亮？睡眠时呢？

关机后鼠标亮，睡眠不亮

**Comment by DrKoschei** [comment]
一样，但过一段时间鼠标就会灭了，感觉是余电。

**Comment by TYan917** [comment]
> 一样，但过一段时间鼠标就会灭了，感觉是余电。

我这边关机一晚上了还没断电，如果是睡眠是和CPU风扇一起断电的，也可以正常鼠标唤醒

**Comment by run6** [comment]
将BIOS中的USB唤醒之类的关掉试试，不过这样应该会对睡眠有影响，看你需要了

**Comment by TYan917** [comment]
> 将BIOS中的USB唤醒之类的关掉试试，不过这样应该会对睡眠有影响，看你需要了

我试了关掉BIOS的USB唤醒，鼠标问题依然存在，另外睡眠后点击鼠标按键，鼠标灯会自动亮起。
config.plist文件是否有唤醒功能开关？

**Comment by Fantasy315** [comment]
关闭usb power on s4 s5。大概就是在关机时还能usb供电的意思

**Comment by TYan917** [comment]
> 关闭usb power on s4 s5。大概就是在关机时还能usb供电的意思

问题解决，非常感谢

**Comment by TYan917** [comment]
> 处理器是：i5 9400F
> 主板：B360M 迫击炮
> 鼠标：雷蛇蝰蛇标准版
> 使用驱动为：USBPower.kext（config.plist已经启动USBPower驱动）
> 根据使用描述内将USB驱动内机器型号改为iMac Pro 1，1。发现关机后鼠标不断电，指示灯还持续亮，重新插拔后不亮。睡眠正常。
> 还请大神帮忙找下原因，谢谢！
