### ISSUE TITLE
睡眠补丁

### ISSUE THREAD

**Issue by ArchFeh** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#5]
经过我的研究发现，OpenCore睡眠补丁的作用是在你开启电能小憩的情况下阻止自动唤醒实现自动睡眠的功能，如使用此补丁，仍需打开电能小憩，否则无法自动睡眠。希望可以修改一下change log，原来的很容易引起歧义。

**Comment by GeQ1an** [comment]
好的，感谢提醒。更新后我便没有在家里，今天下午回家后我会再次进行测试，以修改更新记录。

**Comment by ArchFeh** [comment]
好的，希望测试下来和我的结果也一致！另：小弟fork了你的EFI进行了自定义修改，感谢分享！

**Comment by GeQ1an** [comment]
经过测试，果然如你所说，感谢。
