### ISSUE TITLE
能使用Rx 5500XT 吗

### ISSUE THREAD

**Issue by cyl528656253** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#56]

**Comment by conradlyn** [comment]
可以，我用的就是。完全免驱。
注意在boot arg后面加参数 agdpmod=pikera。否则会启动到后面黑屏（没死机，但是显示器一片灰黑）。

**Comment by cai23511** [comment]
> 可以，我用的就是。完全免驱。
> 注意在boot arg后面加参数 agdpmod=pikera。否则会启动到后面黑屏（没死机，但是显示器一片灰黑）。

请问在Windows下如何添加这个参数呢

**Comment by cyl528656253** [comment]
这是需要在 config 文件里面的开机启动项加
