### ISSUE TITLE
只有核显没有独显的话，主板的DP、DVI和HDMI接口都能正常使用吗？还有是不是钛金版有影响吗？

### ISSUE THREAD

**Issue by JinElias** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#59]
只有核显没有独显的话，主板的DP、DVI和HDMI接口都能正常使用吗？还有是不是钛金版有影响吗？

**Comment by GeQ1an** [comment]
DP 和 HDMI 是没问题的，迫击炮钛金板与普通版都可以使用，我不是加括号了吗？

**Comment by JinElias** [comment]
DVI 呢 正常吗？

**Comment by JinElias** [comment]
楼主用的是钛金版  还是普通版？

**Comment by JinElias** [comment]
@GeQ1an  纯核显的DVI 呢 正常吗？  楼主用的是钛金版 还是普通版？

**Comment by GeQ1an** [comment]
> @GeQ1an 纯核显的DVI 呢 正常吗？ 楼主用的是钛金版 还是普通版？

抱歉，我没有条件测试 DVI 接口。至于主板，我用的是普通版，钛金板和普通版除了外观和主板型号外没有区别。

**Comment by JinElias** [comment]
> > @GeQ1an 纯核显的DVI 呢 正常吗？ 楼主用的是钛金版 还是普通版？
> 
> 抱歉，我没有条件测试 DVI 接口。至于主板，我用的是普通版，钛金板和普通版除了外观和主板型号外没有区别。

好的，谢谢，那我就买普通版的

**Comment by GeQ1an** [comment]
> > > @GeQ1an 纯核显的DVI 呢 正常吗？ 楼主用的是钛金版 还是普通版？
> > 
> > 
> > 抱歉，我没有条件测试 DVI 接口。至于主板，我用的是普通版，钛金板和普通版除了外观和主板型号外没有区别。
> 
> 好的，谢谢，那我就买普通版的

哪个搞活动更优惠就买哪个。
