### ISSUE TITLE
9400+rx480 判断独显硬解情况

### ISSUE THREAD

**Issue by c1awn** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#61]
videoproc检测是核显630双硬解，不像您截图的独显，请问我这样算独显硬解了么？hevc视频测试观看比较卡顿。下面是截图    
<img width="826" alt="截屏2020-05-15 17 43 33" src="https://user-images.githubusercontent.com/29470764/82038094-9af26a00-96d5-11ea-870a-2e80a64b6393.png">

**Comment by myd986** [comment]
同问

**Comment by c1awn** [comment]
> 同问

我剪了几次4K片子，特意不用代理文件，独显满载运行。剪辑拖来拖去、导出母版文件等，未出现卡顿。独显硬解应该没问题。有个BruceX-8K测试机子性能的素材可以搜着试试。
