### ISSUE TITLE
蓝牙不能接USB一分二hub，会导致睡眠失败

### ISSUE THREAD

**Issue by c1awn** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#62]
MSI B360M迫击炮只有一个9针usb2.0接口，而如果机箱面板有usb2.0，94360CD无线网卡的蓝牙也要接usb2.0，可能用USB一分二来解决接口不足。经测试，不管usb一分二是否内建，都不能正常睡眠。表现是屏幕变黑、主机风扇转、主板灯亮。
蓝牙usb直接接主板9针USB即可正常睡眠。

**Comment by bowenqiang** [comment]
原来是这个原因导致的不能睡眠？我后来直接关闭了睡眠。

**Comment by c1awn** [comment]
> 原来是这个原因导致的不能睡眠？我后来直接关闭了睡眠。
Xjin的教程说蓝牙不能在hub上内建，我之前不信。。。

**Comment by ihxperfect** [comment]
我也是用的9针扩，还是一分四，最开始怎么都不能睡眠，后面勾选了小憩反而可以了。
但是蓝牙插在一分四上面睡眠久了容易无响应一直没解决，b360m这种9针不够的真的是找不到解决办法了。

**Comment by c1awn** [comment]
> 我也是用的9针扩，还是一分四，最开始怎么都不能睡眠，后面勾选了小憩反而可以了。
> 但是蓝牙插在一分四上面睡眠久了容易无响应一直没解决，b360m这种9针不够的真的是找不到解决办法了。
蓝牙接在一分四上面开小憩自动和手动睡眠都正常？这就奇怪了，我接一分二不管小憩是否开启，都不能正常睡眠。

**Comment by c1awn** [comment]
另外，虽然现在睡眠OK了，包括自动和手动睡眠，睡一晚唤醒也没出现失败的情况。不过有个地方不知道是否有人注意到，从睡眠唤醒后出现登录界面，不输入密码登录而是点取消（比如不小心碰到鼠标但是又不想登录），则又出现屏幕变黑、主机风扇转、主板灯亮的情况，不确定是系统bug还是个例。

**Comment by Fantasy315** [comment]
一个USB2.0用4针就可以了，九针其实是两个USB2.0接口。你可以试试用其中4个针脚接蓝牙。用其余4个针脚接前置USB2.0

**Comment by c1awn** [comment]
> 一个USB2.0用4针就可以了，九针其实是两个USB2.0接口。你可以试试用其中4个针脚接蓝牙。用其余4个针脚接前置USB2.0

试了下，另外一个基本插不进去，放弃了前置面板2.0，毕竟前置3.0可以用。

**Comment by ihxperfect** [comment]
> 另外，虽然现在睡眠OK了，包括自动和手动睡眠，睡一晚唤醒也没出现失败的情况。不过有个地方不知道是否有人注意到，从睡眠唤醒后出现登录界面，不输入密码登录而是点取消（比如不小心碰到鼠标但是又不想登录），则又出现屏幕变黑、主机风扇转、主板灯亮的情况，不确定是系统bug还是个例。

能说一下怎么搞定的吗？

**Comment by c1awn** [comment]
> > 另外，虽然现在睡眠OK了，包括自动和手动睡眠，睡一晚唤醒也没出现失败的情况。不过有个地方不知道是否有人注意到，从睡眠唤醒后出现登录界面，不输入密码登录而是点取消（比如不小心碰到鼠标但是又不想登录），则又出现屏幕变黑、主机风扇转、主板灯亮的情况，不确定是系统bug还是个例。
> 
> 能说一下怎么搞定的吗？

关闭设置里的共享，关闭handoff

**Comment by naiqiule** [comment]
既然9针无从下手，是否可以考虑从3.0下手（除了9针2.0主板上还有一个19针3.0和一个TYPE-E接口）
例如我的机箱有两个USB2.0需要一个9针口，一个3.0需要一个19针口
那么买一个19针转9针转换器接2.0
再买一个TYPE-E转19针接3.0
这样可以保证蓝牙USB直接插主板不影响蓝牙内建

**Comment by ihxperfect** [comment]
> 一个USB2.0用4针就可以了，九针其实是两个USB2.0接口。你可以试试用其中4个针脚接蓝牙。用其余4个针脚接前置USB2.0

感谢提醒，我直接把一分四接头退针了四针，然后塞进去蓝牙的两针，现在蓝牙是直接接在主板了。
目前看来睡眠后蓝牙没有卡死，多用几天看看。

**Comment by ihxperfect** [comment]
> > > 另外，虽然现在睡眠OK了，包括自动和手动睡眠，睡一晚唤醒也没出现失败的情况。不过有个地方不知道是否有人注意到，从睡眠唤醒后出现登录界面，不输入密码登录而是点取消（比如不小心碰到鼠标但是又不想登录），则又出现屏幕变黑、主机风扇转、主板灯亮的情况，不确定是系统bug还是个例。
> > 
> > 
> > 能说一下怎么搞定的吗？
> 
> 关闭设置里的共享，关闭handoff

我主要就是想用handoff，所以还是折腾了一下。参考我楼上回复，目前一切正常。

**Comment by naiqiule** [comment]
> > > > 另外，虽然现在睡眠OK了，包括自动和手动睡眠，睡一晚唤醒也没出现失败的情况。不过有个地方不知道是否有人注意到，从睡眠唤醒后出现登录界面，不输入密码登录而是点取消（比如不小心碰到鼠标但是又不想登录），则又出现屏幕变黑、主机风扇转、主板灯亮的情况，不确定是系统bug还是个例。
> > > 
> > > 
> > > 能说一下怎么搞定的吗？
> > 
> > 
> > 关闭设置里的共享，关闭handoff
> 
> 我主要就是想用handoff，所以还是折腾了一下。参考我楼上回复，目前一切正常。

我看了我的蓝牙，有6根线连着，上面一排4针和下面一排中间两针，请问这个要怎么搞？如果用分线器的话

**Comment by ihxperfect** [comment]
> > > > > 另外，虽然现在睡眠OK了，包括自动和手动睡眠，睡一晚唤醒也没出现失败的情况。不过有个地方不知道是否有人注意到，从睡眠唤醒后出现登录界面，不输入密码登录而是点取消（比如不小心碰到鼠标但是又不想登录），则又出现屏幕变黑、主机风扇转、主板灯亮的情况，不确定是系统bug还是个例。
> > > > 
> > > > 
> > > > 能说一下怎么搞定的吗？
> > > 
> > > 
> > > 关闭设置里的共享，关闭handoff
> > 
> > 
> > 我主要就是想用handoff，所以还是折腾了一下。参考我楼上回复，目前一切正常。
> 
> 我看了我的蓝牙，有6根线连着，上面一排4针和下面一排中间两针，请问这个要怎么搞？如果用分线器的话

我的蓝牙只有两根线，你搜搜9针usb每根针的用途，然后就会明白怎么操作了

**Comment by myd986** [comment]
网卡usb是2.0，只有四根针，可以把四根针直接连接主板，另外四根接hub分给前面板用

**Comment by naiqiule** [comment]
> 网卡usb是2.0，只有四根针，可以把四根针直接连接主板，另外四根接hub分给前面板用

我的蓝牙是6根线，不知道该怎么拆，还是用转换器接另外两个口试试了

**Comment by c1awn** [comment]
> > 网卡usb是2.0，只有四根针，可以把四根针直接连接主板，另外四根接hub分给前面板用
> 
> 我的蓝牙是6根线，不知道该怎么拆，还是用转换器接另外两个口试试了
