### ISSUE TITLE
是否可以考虑下次更新加速最新的魔改1.3.9WEG

### ISSUE THREAD

**Issue by naiqiule** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#63]
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1847847&extra=page%3D1&page=1&mobile=yes

如上，似乎最新魔改版相对原版igfxfw=2优化更好一些，或者如果没有考虑如果我想换成魔改版是否把igfxfw=2参数去掉然后直接替换魔改版文件和最新lilu？谢谢

**Comment by GeQ1an** [comment]
对于魔改版本，建议自行替换使用，不会将其加入到 EFI 中。

**Comment by naiqiule** [comment]
好的 多谢 已经替换测试成功 谢谢！~
