### ISSUE TITLE
PS2键盘 开机与进系统都无法识别问题

### ISSUE THREAD

**Issue by laogaoda** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#65]
请问有没有办法解决呢，不敢乱装kexts，感谢

**Comment by GeQ1an** [comment]
下载 [OC 完整包](https://github.com/acidanthera/OpenCorePkg/releases)，解压后将里面 EFI--OC--Drivers 中的 Ps2KeyboardDxe.efi 添加到 EFI 分区，并在配置文件 UEFI > Drivers 处添加该条目。
