### ISSUE TITLE
请问一下，有尝试过去掉Slide=129么？

### ISSUE THREAD

**Issue by SuperNG6** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#7]
前几天看见帖子说B360也可以开启原生NVRAM了，看外网说似乎可以去掉Slide值，请问楼主有尝试过么？我这也准备折腾看看
https://www.hackintosh-forum.de/forum/thread/46154-natives-nvram-auf-dem-z390-durchbruch/?pageNo=1

**Comment by GeQ1an** [comment]
呃……我已经忘记了 Slide 这回事，所以没有尝试，不过你倒是提醒我了。
晚些时候我会尝试去掉 Slide 值。

**Comment by ArchFeh** [comment]
亲测去掉了可以正常使用

**Comment by SuperNG6** [comment]
感谢回复，我晚些时候也配置一下
在 2020年2月13日 +0800 PM6:29，YuGu <notifications@github.com>，写道：

**Comment by SuperNG6** [comment]
去掉slide值后应该大部分主板都可以使用了，配置起来不需要那么挑主板了
在 2020年2月13日 +0800 PM6:39，SuperNG6 <sleele@gmail.com>，写道：

**Comment by GeQ1an** [comment]
经过我今晚反复测试，去掉 Slide=129 启动参数后并非完美。
删除 Slide=129 后，关机再开机不显示苹果 logo，黑屏状态直接进入登陆界面，直接在系统内选择重启会正常显示苹果 logo。
重新添加回 Slide=129 后，关机再开机、直接重启，均正常显示苹果 logo，不会出现黑屏状态直接进入登陆界面的情况。
希望大家也给一下反馈，这个状况是否只有我一人。

**Comment by SuperNG6** [comment]
我这正常，原因可能在别的地方，再排查一下吧，可能是oc配置或者bios的缘故

GeQ1an <notifications@github.com>于2020年2月17日 周一上午6:12写道：

**Comment by GeQ1an** [comment]
> 我这正常，原因可能在别的地方，再排查一下吧，可能是oc配置或者bios的缘故 GeQ1an <notifications@github.com>于2020年2月17日 周一上午6:12写道：
> […](#)

除非是你们修改了什么设置…… 要不然我配置好的 OC 文件和 BIOS 设置，你们都没问题怎么我有问题……🌚🌚🌚

**Comment by SuperNG6** [comment]
我用的是自己的

GeQ1an <notifications@github.com>于2020年2月17日 周一下午7:25写道：

**Comment by GeQ1an** [comment]
> 我用的是自己的 GeQ1an <notifications@github.com>于2020年2月17日 周一下午7:25写道：
> […](#)

奥，如此的话不发配置文件和没说一样。

**Comment by ArchFeh** [comment]
> > 我用的是自己的 GeQ1an [notifications@github.com](mailto:notifications@github.com)于2020年2月17日 周一下午7:25写道：
> > […](#)
> 
> 奥，如此的话不发配置文件和没说一样。

打开Booter-Quirks下的DevirtualiseMmio试试看

**Comment by SuperNG6** [comment]
> > 我用的是自己的 GeQ1an [notifications@github.com](mailto:notifications@github.com)于2020年2月17日 周一下午7:25写道：
> > […](#)
> 
> 奥，如此的话不发配置文件和没说一样。

我觉得你这个情况可能和CSM有关，检查一下吧

**Comment by GeQ1an** [comment]
> > > 我用的是自己的 GeQ1an [notifications@github.com](mailto:notifications@github.com)于2020年2月17日 周一下午7:25写道：
> > > […](#)
> > 
> > 
> > 奥，如此的话不发配置文件和没说一样。
> 
> 我觉得你这个情况可能和CSM有关，检查一下吧

经过反复测试，关闭「Windows 10 WHQL支持」后，一切正常，谢谢。
