### ISSUE TITLE
三码会有什么影响吗？

### ISSUE THREAD

**Issue by zq535228** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#70]
在您的文章里，提到了三码的问题，我也不会弄，目前已经正常运行2周时间了，没发现什么问题。
请问三码不去管他，可以吗，会发生什么问题。

**Comment by GeQ1an** [comment]
会影响 iCloud 等 Apple 服务。

**Comment by zq535228** [comment]
还有一个问题，我的这个可以保持更新吗？
![image](https://user-images.githubusercontent.com/45892397/85204186-45008a00-b345-11ea-8936-2accd54adb10.png)

**Comment by Went1ng** [comment]
三码等其他的问题解决可以参考B站的：BV1nE411j7Wm（视频作者非本人）
更新的话，有软件更新和系统更新，软件一般来说没有什么问题，系统的话就是小更新可以（如15.4更新到15.5）至于大更新不太了解，建议不要。
个人意见，感谢采纳。

**Comment by zq535228** [comment]
谢谢，went1ng，thank you very much.
