### ISSUE TITLE
看见只有你一直在更新，发一个感谢帖

### ISSUE THREAD

**Issue by qwetrz007sh** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#72]
感谢老哥让我体验成功，看见只有你一直在更新，就选择你的EFI
简单说说配置，直接全部复制老哥的oc EFI
8700K
微星z370 银环蛇
RX570 4g
内存随便买的

现在只是单纯的体验系统，有空剪个视频试试看看有问题没。
已关注tg频道，貌似没更新？TG吹水群么？
已送老哥一瓶红牛钱

**Comment by GeQ1an** [comment]
感谢支持，更新三年后项目快要说再见了。
