### ISSUE TITLE
这个板子是hdmi无解吗

### ISSUE THREAD

**Issue by Odysseusq** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#77]
rt，完全按照教程走，用hdmi到进度条加载whatevergreen的位置就黑屏，但用了别的地方某个大哥的clover就成功，疑惑

**Comment by Went1ng** [comment]
之前用过clover现在转oc最好先重置nvram

**Comment by Odysseusq** [comment]
解决了，参考@OCD0711的efi，在device property中按照以下设置即可解决hdmi无信号的问题（我是无核显，改了platform-id，有独显请勿修改此项）
![image](https://user-images.githubusercontent.com/57209123/85711134-8d3ef400-b719-11ea-97ce-7f987e4ee505.png)

**Comment by Mr-power** [comment]
> 解决了，参考@OCD0711的efi，在device property中按照以下设置即可解决hdmi无信号的问题（我是无独显，改了platform-id，有独显请勿修改此项）
> ![image](https://user-images.githubusercontent.com/57209123/85711134-8d3ef400-b719-11ea-97ce-7f987e4ee505.png)
您好，给个efi。我也是只有核显，邮箱1162255758@qq.com
不胜感激。用了这个efi。开机报错，IOConsoleUsers:gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0  。难不成hdmi。启动不了？。系统安装好了 10.15.5.！
