### ISSUE TITLE
不能进oc引导界面

### ISSUE THREAD

**Issue by Mr-Baiding** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#8]
和博主是一样的配置，主办也按照给的方法设定了，但是引导的时候直接跳过引导盘，启动Windows了。调整参数后也不能进入oc界面。所以想问问博主之前有人反映过类似的情况吗？

**Comment by GeQ1an** [comment]
十分抱歉，因为我没有安装 Windows 系统，所以未曾遇到过类似的情况。
请问是单磁盘双系统？还是双磁盘各一个系统？
前者的话，请参考 [xjn’s blog](https://blog.xjn819.com/) 文章 [使用 OpenCore 引导黑苹果](https://blog.xjn819.com/?p=543) 的「3.2 建立自己的开机选择系统目录」进行操作。
后者的话，请在 BIOS 内设置启动盘顺序，将主系统磁盘排在最上方，开机时可按 F11 临时切换启动盘启动不同系统。

**Comment by i0Ek3** [comment]
@Mr-Baiding 如果你是用黑果小兵的镜像做的启动盘，你需要删除WinPE分区里的东西，然后重新启动应该就可以进入OC了。

**Comment by lbq1223android** [comment]
> 和博主是一样的配置，主办也按照给的方法设定了，但是引导的时候直接跳过引导盘，启动Windows了。调整参数后也不能进入oc界面。所以想问问博主之前有人反映过类似的情况吗？

我也进不去 你后来解决这个问题了吗

**Comment by lbq1223android** [comment]
> @Mr-Baiding 如果你是用黑果小兵的镜像做的启动盘，你需要删除WinPE分区里的东西，然后重新启动应该就可以进入OC了。

怎么删除？  我直接删除文件后 u盘引导损坏了

**Comment by bowenqiang** [comment]
@Mr-Baiding @lbq1223android  同样问题。我是先用另外一个人的EFI （https://github.com/ArchFeh/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI-without-core-graphic））完成系统的安装，然后进入系统后换成这里的EFI就可以了。那个人的EFI好像声卡设置不对，换成这里的EFI就一切正常了。

**Comment by CalesQ** [comment]
> > @Mr-Baiding 如果你是用黑果小兵的镜像做的启动盘，你需要删除WinPE分区里的东西，然后重新启动应该就可以进入OC了。
> 
> 怎么删除？ 我直接删除文件后 u盘引导损坏了

你删除了吗，怎么删除

**Comment by gogoclothes** [comment]
博主的oc没有问题，可以支持双系统。我的配置：b360m, 5500xt (这个要加参数，引导黑屏，博主有提到）
我两个ssd，一个Mac，一个win。
先装Macos，然后用oc更改efi下面的config：Misc-其他设置-boot-然后点击：show picker（默认是关闭的，就是你看不到oc的启动引导选择界面）

开启之后，你重新启动就用选项了，默认好像是5s，你可以自己加到30s，也就是更改timeout的选项。

然后再装win，最后进入bios设置第一启动为mac所在的ssd。
再次开机，你就可以看到可以选择win和mac啦～

非常感谢博主的efi～（已donate一杯咖啡～☕️）
祝大家玩得开心～～～

**Comment by ShawLocke** [comment]
我是黑果小兵的10.15.7镜像制作的安装盘，在DiskGenius中删除WEPE分区，删除EFI分钟的所有文件夹，然后下载博主的EFI，然后拖入（或者Ctrl+C，然后Ctrl+V）到EFI分区，重启PC，按Del键（不同主板可能不同）进行BIOS，选择启动模式为UEFI，第一启动项为UEFI USB Key，保存并退出，PC会自动重启，然后按Option/Alt键，这样就会出现引导选择界面。

重点：1. 记得按Option/Alt键；2. 微星B360M迫击炮钛金板可能会出现无法识别U盘的现象，只需要拔插一次，然后重试即可。

**Comment by SLin0218** [comment]
@gogoclothes  感谢，  这个问题 我重启无数次，结果原来是默认进入了其他引导，因为我 mac os 还没有安装 直接进了pe ， 删除pe 后 直接进入了windows 10

**Comment by SLin0218** [comment]
如果是安装系统
先将 `show picker` 设置为 `true`，安装完成后再修改为 `false`
@Mr-Baiding
