### ISSUE TITLE
板载 9pin usb 2.0

### ISSUE THREAD

**Issue by niqk** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#87]
你好 不知道你有没有测试板载的9pin usb 2.0是否工作正常？ 我找了很多efi 都有点问题 机箱自带的口 usb2.0 无法使用， 接pcie网卡的话 因为usb 2.0不工作 也没法识别蓝牙

**Comment by Went1ng** [comment]
可以正常使用，机箱上的的usb2.0可以不要，非要用usb hub连接会影响睡眠

**Comment by niqk** [comment]
n那你接pcie网卡的蓝牙怎么弄的？直接走m.2？

**Comment by Went1ng** [comment]
这迫击炮的主板，只有一个9针usb2.0
就只能把网卡的蓝牙插在这上面
我的机箱只有两个前置的usb3.0和音频接口
所以一个usb2.0的话，也足够了。

**Comment by niqk** [comment]
主板有俩吧 msi b460m的话

**Comment by Went1ng** [comment]
这是MSI B360 mortar的主板EFI 应该是不适合MSI B460 mortar

**Comment by niqk** [comment]
哦哦 不好意思 之前没注意到。。。打扰了

**Comment by pengpaige** [comment]
> 你好 不知道你有没有测试板载的9pin usb 2.0是否工作正常？ 我找了很多efi 都有点问题 机箱自带的口 usb2.0 无法使用， 接pcie网卡的话 因为usb 2.0不工作 也没法识别蓝牙

遇到了相同的问题，请问最后找到解决了吗？

**Comment by niqk** [comment]
用 9pin 转usb2.0的线 可以自己制作 然后拉出来从机箱后的usb2.0连接
On Sat, 17 Oct 2020 at 03:44, pengpaige <notifications@github.com> wrote:

你好 不知道你有没有测试板载的9pin usb 2.0是否工作正常？ 我找了很多efi 都有点问题 机箱自带的口 usb2.0 无法使用，
接pcie网卡的话 因为usb 2.0不工作 也没法识别蓝牙

遇到了相同的问题，请问最后找到解决了吗？

—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI/issues/87#issuecomment-710502964>,
or unsubscribe
