### ISSUE TITLE
第一次装黑果，请问EFI分区复制到黑果小兵的哪个分区，直接替换EFI分区进入不了安装界面

### ISSUE THREAD

**Issue by xuconnery** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#88]
第一次装黑果，除了显卡是迪兰的570，CPU主板均与git主一样。

因为看到OC是趋势，所以想直接从OC开始。

黑果小兵的镜像下载的是macOS Catalina 10.15.5 19F2200 正式版 Clover 5119/OC/WEPE同时支持INTEL及AMD原版镜像，有EFI分区、OC分区。

删除小兵的EFI分区、OC分区里的EFI文件夹，将git主的EFI复制进去，直接连clover安装界面进不去。

保留小兵的EFI分区里的EFI文件夹，删除OC分区里的EFI文件夹，将git主的EFI复制进去，进入clover安装界面，跑完代码也进入不了macOS安装界面。

应该怎么弄？

PS，已经参照说明替换了git主config.plist的四码。

**Comment by xuconnery** [comment]
小兵的EFI分区，用git主的EFI文件夹里BOOT和OC复制进去，保留Clover文件夹。同时删除小兵的OC分区里的EFI文件夹，用git主的EFI复制进去。

报错如下：

**Comment by Went1ng** [comment]
报错什么。

**Comment by xuconnery** [comment]
> 报错什么。

OCB：StartImage failed - Already started
Halting on critical error

已经解决装上啦~~

**Comment by Went1ng** [comment]
之前安装也是出现过这个报错，第一次安装有可能会停在这里，进入系统之后可以改回去的
