### ISSUE TITLE
奋威 BCM94360CD wifi蓝牙都正常可用，但是隔空投送有较大问题

### ISSUE THREAD

**Issue by qwetrz007sh** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#89]
隔空投送显示了一次我其他的设备，之后就不显示设备了。然后过1-2小时，又可以用一次，然后又不显示设备了，怎么回事呢。
是跟我主板有关系么，我用的微星z370银环蛇

**Comment by GeQ1an** [comment]
暂未出现过此问题，建议逐步排查问题所在。

**Comment by SkyGrass** [comment]
蓝牙卡顿吗

**Comment by livn519** [comment]
我也出现了同样的问题，同款网卡，先用黑果小兵的原版镜像引导时隔空投送都能够正常使用，更新了EFI和修改机型与三码之后隔空投送就变得时好时坏，要么不显示设备要么显示设备点击发送没反应，或者过好久才发过来，iPhone上和mac上都是同样的问题，希望你能够解答

**Comment by livn519** [comment]
> 隔空投送显示了一次我其他的设备，之后就不显示设备了。然后过1-2小时，又可以用一次，然后又不显示设备了，怎么回事呢。
> 是跟我主板有关系么，我用的微星z370银环蛇

请问你的问题解决了么？

**Comment by SkyGrass** [comment]
很意外，我没有这样的情况。我用的是BCM94360CS2。

**Comment by qwetrz007sh** [comment]
> > 隔空投送显示了一次我其他的设备，之后就不显示设备了。然后过1-2小时，又可以用一次，然后又不显示设备了，怎么回事呢。
> > 是跟我主板有关系么，我用的微星z370银环蛇
> 
> 请问你的问题解决了么？

木有，我没用黑苹果了，换了amd了。

**Comment by GeQ1an** [comment]
隔空投送，有些时候白果也有问题，什么都不动有些时候自己又好了（包括黑果）。
