### ISSUE TITLE
请问下苹果卡BCM943602CS需要改什么吗？

### ISSUE THREAD

**Issue by joshzda** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#9]
请教下大佬，我的无线蓝牙卡是BCM943602CS，之前用clover一直免驱也没额外配置什么。
之前几天试了你的EFI，无线ok但是蓝牙有点不稳定，有时候能搜索到但是连不上，或者反复的断开重连。
我又切回原本的clover，又可以正常使用。。看了一些oc的资料，好像没找到什么解决方案。。
求教。

**Comment by GeQ1an** [comment]
这个问题就有点奇怪了，Clover 中免驱，理论上 OC 也可以直接使用。
是白果拆机的 BCM943602CS 吗？如果是的话，可以需要更换转接板。
至于为什么会这样，可能是底层的原因吧（我猜的）。

**Comment by joshzda** [comment]
这两天突然又可以用了，什么都没有改。。
