### ISSUE TITLE
大家有否遇到过关机变重启？

### ISSUE THREAD

**Issue by xuconnery** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#90]
CPU和主板与GeQ1an大神相同。安装后使用一切正常。

过了2天后，遇到问题：关机变成重启。

排查后，估计可能与「USB设备从S3/S4/S5唤醒」开启有关，我当时：主板USB口插了CSR8510a10的蓝牙适配器（用来连接斐讯R1音箱），罗技的无线键鼠蓝牙适配器，一根USB线（已拔下手机）。将USB线拔出后，关机正常。

此后一两天，关机都正常了。到今天中午，关机再次变成了重启！目前主板USB口只插了：CSR8510a10的蓝牙适配器（用来连接斐讯R1音箱），罗技的无线键鼠蓝牙适配器。

请教下：GeQ1an大神教程中开启「USB设备从S3/S4/S5唤醒」是做什么用的，可否关闭？

**Comment by scalpelxxx** [comment]
对于10.15系统，在配置文件中打开
PowerTimeoutKernelPanic=true

**Comment by xuconnery** [comment]
@scalpelxxx 好，我试试

**Comment by GeQ1an** [comment]
我没遇到过-。-
