### ISSUE TITLE
安装完成后，使用仓库里面的EFI 文件替换后，无法正常启动

### ISSUE THREAD

**Issue by python8384** [GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI#99]
1、CPU,主板配置 和readme里面一模一样， 显卡使用 蓝宝石  RX 5500xt  ；
2、安装过程中经常出现黑屏情况，现在options 里面的的默认引导参数已经加上了agdpmod=pikera 
3、安装完成后，使用仓库里面的EFI替换后，正常硬盘引导，出现苹果logo，进度条走到小一半，一闪，后面就黑屏了，只能强制关机，几乎每次都是这样（除了安装系统成功那次可以正常进入系统）
4、操作系统版本 使用黑果小兵最新发布的 10.15.6 版本；

不知道这种情况 怎么解决，望大神赐教。

@GeQ1an

**Comment by Went1ng** [comment]
似乎遇到过相同情况
CPU是9400，显卡RX574   显示器1080P其他相同
EFI修改了：
三码和ROM,关掉了9600K用的变频文件，和非4K显示器的设置，后来又定制了USB
我的解决方法：
1，重新检查主板BIOS设置
2，用显卡DP口连接显示器（显示器没有DP可以转接）
3，不过多的使用不是必要的USB设备或其他设备（好像还拔掉了无线网卡）


如果用U盘引导失败，可以尝试将EFI放入硬盘直接开机引导「可以用其他进系统的方法（clover或其他oc），或者Windows，PE可以修改硬盘的软件中操作」

感谢参考

**Comment by GeQ1an** [comment]
仔细检查 BIOS 设置及核显相关设置。
